/**
 * AIfaFocus 1-Click Code Remediation Engine (v2)
 * 
 * Набор вспомогательных приёмов клавиатурной доступности:
 * 1. Двухцветный контур фокуса клавиатуры (:focus-visible, WCAG 2.4.7, контраст ≥ 3:1 на любом фоне)
 * 2. Внедрение ссылки перехода к основному содержимому с автоопределением языка по <html lang> (WCAG 2.4.1)
 * 3. Закрытие открытого окна по Escape, если у окна есть кнопка «Закрыть» (не перехватывает defaultPrevented)
 * 4. Восстановление доступных подписей кнопок и ссылок строго из авторских title, img[alt], svg title (WCAG 4.1.2)
 * 5. Уважение настроек снижения движения (prefers-reduced-motion, WCAG 2.3.3)
 * 
 * Zero-dependency: не требует внешних библиотек, чистый ES5 JS и CSS.
 * ВАЖНО: это вспомогательная мера для пользователей клавиатуры. Патч НЕ устраняет
 * найденные нарушения в коде сайта и НЕ даёт соответствия WCAG, ADA или EAA.
 */

export interface PatchThreat {
  code: string;
  category?: string;
  severity?: string;
  title?: string;
  evidence?: string;
}

export interface PatchOptions {
  domain?: string;
  locale?: string;
  threats?: PatchThreat[];
  accentColor?: string;
  includeSkipLink?: boolean;
  includeFocusOutline?: boolean;
  includeMotionGuard?: boolean;
  includeModalEscape?: boolean;
  includeAriaFixer?: boolean;
}

export interface GeneratedPatch {
  css: string;
  js: string;
  embedHtml: string;
  summary: {
    techniquesCount: number;
    fixedIssuesCount: number; // Сохранено для обратной совместимости API
    features: string[];
    cssBytes: number;
    jsBytes: number;
    totalBytes: number;
  };
}

/**
 * Очистка домена от недопустимых символов для безопасной вставки в комментарии.
 * Пропускает только [a-z0-9.-], блокируя разрыв комментариев через `* /`.
 */
export function sanitizeDomainForComment(domain: string): string {
  const sanitized = String(domain || '')
    .toLowerCase()
    .replace(/[^a-z0-9.-]/g, '');
  return sanitized || 'example.com';
}

export function generateAIfaFocusPatch(options: PatchOptions = {}): GeneratedPatch {
  const {
    domain = 'example.com',
    locale = 'en',
    threats = [],
    includeSkipLink = true,
    includeFocusOutline = true,
    includeMotionGuard = true,
    includeModalEscape = true,
    includeAriaFixer = true,
  } = options;

  const safeDomain = sanitizeDomainForComment(domain);
  const lang = (locale || 'en').toLowerCase().slice(0, 2);

  const features: string[] = [];
  let techniquesCount = 0;

  // ─── 1. CSS PATCH ──────────────────────────────────────────────────────────
  const cssLines: string[] = [
    `/* ==========================================================================`,
    `   AIfaFocus 1-Click Accessibility Patch`,
    `   Target Domain: ${safeDomain}`,
    `   Generated by AIfa Works / CODE Eternal (https://aifa.works)`,
    `   Temporary keyboard-access helper. It does NOT make a site conform to`,
    `   WCAG, the ADA or the EAA: fix the findings in your templates and re-scan.`,
    `   ========================================================================== */`,
    ``,
  ];

  if (includeFocusOutline) {
    techniquesCount += 1;
    features.push(
      lang === 'ru'
        ? 'Двухцветный контур фокуса (:focus-visible, контраст ≥ 3:1 на любом фоне)'
        : lang === 'es'
        ? 'Contorno de foco bicolor (:focus-visible, contraste ≥ 3:1 en cualquier fondo)'
        : lang === 'zh'
        ? '双色焦点轮廓 (:focus-visible，任意背景对比度 ≥ 3:1)'
        : 'Dual-color focus outline (:focus-visible, ≥ 3:1 contrast on any background)'
    );

    cssLines.push(
      `/* 1. Universal Dual-Color Accessible Focus (WCAG 2.4.7 Focus Visible, AA) */`,
      `/* White inner ring + dark line + white outer ring ensures >= 3:1 contrast on any background */`,
      `:focus-visible {`,
      `  outline: 3px solid #0B1220 !important;`,
      `  outline-offset: 2px !important;`,
      `  box-shadow: 0 0 0 2px #FFFFFF, 0 0 0 7px #FFFFFF !important;`,
      `  transition: outline-offset 0.1s ease !important;`,
      `}`,
      ``,
      `/* Interactive elements explicit focus ring */`,
      `a:focus-visible,`,
      `button:focus-visible,`,
      `input:focus-visible,`,
      `select:focus-visible,`,
      `textarea:focus-visible,`,
      `[tabindex]:focus-visible,`,
      `[role="button"]:focus-visible,`,
      `[role="link"]:focus-visible {`,
      `  outline: 3px solid #0B1220 !important;`,
      `  outline-offset: 2px !important;`,
      `  box-shadow: 0 0 0 2px #FFFFFF, 0 0 0 7px #FFFFFF !important;`,
      `}`,
      ``,
      `/* High contrast mode support (Windows Contrast Themes) */`,
      `@media (forced-colors: active) {`,
      `  :focus-visible,`,
      `  a:focus-visible,`,
      `  button:focus-visible,`,
      `  input:focus-visible,`,
      `  select:focus-visible,`,
      `  textarea:focus-visible,`,
      `  [tabindex]:focus-visible,`,
      `  [role="button"]:focus-visible,`,
      `  [role="link"]:focus-visible {`,
      `    outline: 3px solid Highlight !important;`,
      `    outline-offset: 2px !important;`,
      `    box-shadow: none !important;`,
      `  }`,
      `}`,
      ``
    );
  }

  if (includeSkipLink) {
    techniquesCount += 1;
    features.push(
      lang === 'ru'
        ? 'Ссылка перехода к содержимому (язык по <html lang>)'
        : lang === 'es'
        ? 'Enlace de salto al contenido principal (idioma según <html lang>)'
        : lang === 'zh'
        ? '跳转到主要内容链接（根据 <html lang> 自动选择语言）'
        : 'Skip-to-content link (language matched from <html lang>)'
    );

    cssLines.push(
      `/* 2. Skip to Content Link (WCAG 2.4.1 Bypass Blocks) */`,
      `.aifafocus-skip-link {`,
      `  position: absolute !important;`,
      `  top: -9999px !important;`,
      `  left: 50% !important;`,
      `  transform: translateX(-50%) !important;`,
      `  background: #0B1220 !important;`,
      `  color: #FFFFFF !important;`,
      `  padding: 12px 24px !important;`,
      `  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif !important;`,
      `  font-size: 14px !important;`,
      `  font-weight: 700 !important;`,
      `  text-decoration: none !important;`,
      `  border: 2px solid #FFFFFF !important;`,
      `  border-radius: 0 0 8px 8px !important;`,
      `  box-shadow: 0 8px 30px rgba(0, 0, 0, 0.8), 0 0 0 2px #0B1220 !important;`,
      `  z-index: 2147483647 !important;`,
      `  transition: top 0.2s cubic-bezier(0.16, 1, 0.3, 1) !important;`,
      `}`,
      `.aifafocus-skip-link:focus,`,
      `.aifafocus-skip-link:focus-visible {`,
      `  top: 0 !important;`,
      `  outline: 3px solid #FFFFFF !important;`,
      `  outline-offset: 2px !important;`,
      `}`,
      ``
    );
  }

  if (includeMotionGuard) {
    techniquesCount += 1;
    features.push(
      lang === 'ru'
        ? 'Отключение анимаций при prefers-reduced-motion'
        : lang === 'es'
        ? 'Desactivación de animaciones con prefers-reduced-motion'
        : lang === 'zh'
        ? '在 prefers-reduced-motion 时关闭动画'
        : 'Animation disable on prefers-reduced-motion'
    );

    cssLines.push(
      `/* 3. Vestibular Motion Safety (WCAG 2.3.3 Animation from Interactions) */`,
      `@media (prefers-reduced-motion: reduce) {`,
      `  *, ::before, ::after {`,
      `    animation-duration: 0.01ms !important;`,
      `    animation-iteration-count: 1 !important;`,
      `    transition-duration: 0.01ms !important;`,
      `    scroll-behavior: auto !important;`,
      `  }`,
      `}`,
      ``
    );
  }

  const css = cssLines.join('\n');

  // ─── 2. JS PATCH (Strict ES5) ──────────────────────────────────────────────
  const jsLines: string[] = [
    `/**`,
    ` * AIfaFocus 1-Click Accessibility Injector (ES5)`,
    ` * Domain: ${safeDomain}`,
    ` * (c) CODE Eternal / AIfa Works — https://aifa.works`,
    ` */`,
    `;(function() {`,
    `  'use strict';`,
    `  function initAIfaFocus() {`,
  ];

  if (includeSkipLink) {
    jsLines.push(
      `    /* 1. Skip-to-Content Injection (language derived from <html lang>) */`,
      `    if (!document.querySelector('.aifafocus-skip-link')) {`,
      `      var target = document.querySelector('main, [role="main"], #content, #main, article, h1');`,
      `      if (target) {`,
      `        if (!target.id) target.id = 'aifafocus-main-content';`,
      `        if (!target.hasAttribute('tabindex')) target.setAttribute('tabindex', '-1');`,
      `        var docLang = (document.documentElement.lang || '').slice(0, 2).toLowerCase();`,
      `        var skipText = 'Skip to main content';`,
      `        if (docLang === 'ru') {`,
      `          skipText = '\\u041f\\u0435\\u0440\\u0435\\u0439\\u0442\\u0438 \\u043a \\u043e\\u0441\\u043d\\u043e\\u0432\\u043d\\u043e\\u043c\\u0443 \\u0441\\u043e\\u0434\\u0435\\u0440\\u0436\\u0438\\u043c\\u043e\\u043c\\u0443';`,
      `        } else if (docLang === 'es') {`,
      `          skipText = 'Saltar al contenido principal';`,
      `        } else if (docLang === 'zh') {`,
      `          skipText = '\\u8df3\\u8f6c\\u5230\\u4e3b\\u8981\\u5185\\u5bb9';`,
      `        }`,
      `        var skipLink = document.createElement('a');`,
      `        skipLink.href = '#' + target.id;`,
      `        skipLink.className = 'aifafocus-skip-link';`,
      `        skipLink.textContent = skipText;`,
      `        skipLink.addEventListener('click', function() {`,
      `          target.focus();`,
      `        });`,
      `        if (document.body && document.body.firstChild) {`,
      `          document.body.insertBefore(skipLink, document.body.firstChild);`,
      `        } else if (document.body) {`,
      `          document.body.appendChild(skipLink);`,
      `        }`,
      `      }`,
      `    }`,
      ``
    );
  }

  if (includeModalEscape) {
    techniquesCount += 1;
    features.push(
      lang === 'ru'
        ? 'Закрытие открытого окна по Escape (при наличии кнопки «Закрыть»)'
        : lang === 'es'
        ? 'Cierre de diálogo abierto con Escape (si tiene botón «Cerrar»)'
        : lang === 'zh'
        ? '按 Esc 关闭已打开对话框（若对话框含“关闭”按钮）'
        : 'Close open dialog on Escape (if Close button present)'
    );

    jsLines.push(
      `    /* 2. Escape Listener: closes open dialog if Close button is present */`,
      `    var lastFocusedBeforeModal = null;`,
      `    document.addEventListener('focusin', function(e) {`,
      `      var activeModal = document.querySelector('dialog[open], [role="dialog"][aria-modal="true"], .modal.is-active, .modal.show, .modal[open]');`,
      `      if (!activeModal && e.target) {`,
      `        lastFocusedBeforeModal = e.target;`,
      `      }`,
      `    }, false);`,
      ``,
      `    document.addEventListener('keydown', function(e) {`,
      `      if (e.defaultPrevented) return;`,
      `      var key = e.key || e.keyCode;`,
      `      if (key === 'Escape' || key === 'Esc' || key === 27) {`,
      `        var activeDialog = document.querySelector('dialog[open], [role="dialog"][aria-modal="true"], .modal.is-active, .modal.show, .modal[open]');`,
      `        if (activeDialog) {`,
      `          if (activeDialog.offsetWidth === 0 && activeDialog.offsetHeight === 0 && !activeDialog.open) {`,
      `            return;`,
      `          }`,
      `          var closeBtn = activeDialog.querySelector('[aria-label*="close" i], [aria-label*="\\u0437\\u0430\\u043a\\u0440\\u044b\\u0442\\u044c" i], [aria-label*="cerrar" i], [aria-label*="\\u5173\\u95ed" i], .close-modal, button.close, [data-dismiss="modal"]');`,
      `          if (closeBtn && typeof closeBtn.click === 'function') {`,
      `            closeBtn.click();`,
      `            if (lastFocusedBeforeModal && typeof lastFocusedBeforeModal.focus === 'function') {`,
      `              try { lastFocusedBeforeModal.focus(); } catch (err) {}`,
      `            }`,
      `          }`,
      `        }`,
      `      }`,
      `    }, false);`,
      ``
    );
  }

  if (includeAriaFixer) {
    techniquesCount += 1;
    features.push(
      lang === 'ru'
        ? 'Подстановка подписей кнопок и ссылок строго из title/alt/svg'
        : lang === 'es'
        ? 'Asignación de etiquetas para botones y enlaces solo desde title/alt/svg'
        : lang === 'zh'
        ? '严格从现有 title/alt/svg 提取按钮与链接可访问名称'
        : 'Accessible names for buttons and links strictly from title/alt/svg'
    );

    jsLines.push(
      `    /* 3. Fallback Accessible Names for Icon Buttons & Links (WCAG 4.1.2) */`,
      `    function hasAccessibleName(el) {`,
      `      if (!el) return false;`,
      `      var labelledby = (el.getAttribute('aria-labelledby') || '').trim();`,
      `      if (labelledby) {`,
      `        var ids = labelledby.split(/\\s+/);`,
      `        for (var j = 0; j < ids.length; j++) {`,
      `          var id = ids[j];`,
      `          if (!id) continue;`,
      `          var target = document.getElementById(id);`,
      `          if (target) {`,
      `            var targetText = (target.innerText || target.textContent || '').replace(/\\s+/g, ' ').trim();`,
      `            var targetLabel = (target.getAttribute('aria-label') || '').trim();`,
      `            if (targetText || targetLabel) return true;`,
      `          }`,
      `        }`,
      `      }`,
      `      var ariaLabel = (el.getAttribute('aria-label') || '').trim();`,
      `      if (ariaLabel) return true;`,
      `      var clone = el.cloneNode(true);`,
      `      var hiddenNodes = clone.querySelectorAll('[aria-hidden="true"], script, style, template');`,
      `      for (var h = 0; h < hiddenNodes.length; h++) {`,
      `        if (hiddenNodes[h].parentNode) {`,
      `          hiddenNodes[h].parentNode.removeChild(hiddenNodes[h]);`,
      `        }`,
      `      }`,
      `      var text = (clone.textContent || '').replace(/\\s+/g, ' ').trim();`,
      `      if (text) return true;`,
      `      var imgs = clone.querySelectorAll('img[alt], area[alt], input[type="image"][alt]');`,
      `      for (var m = 0; m < imgs.length; m++) {`,
      `        var alt = (imgs[m].getAttribute('alt') || '').trim();`,
      `        if (alt) return true;`,
      `      }`,
      `      var svgs = clone.querySelectorAll('svg[aria-label], [role="img"][aria-label]');`,
      `      for (var s = 0; s < svgs.length; s++) {`,
      `        var sLabel = (svgs[s].getAttribute('aria-label') || '').trim();`,
      `        if (sLabel) return true;`,
      `      }`,
      `      var tag = el.tagName ? el.tagName.toLowerCase() : '';`,
      `      var type = el.getAttribute('type') ? el.getAttribute('type').toLowerCase() : '';`,
      `      if (tag === 'input' && type === 'image') {`,
      `        var imgAlt = (el.getAttribute('alt') || '').trim();`,
      `        if (imgAlt) return true;`,
      `      }`,
      `      if (tag === 'input' && (type === 'submit' || type === 'reset' || type === 'button')) {`,
      `        var val = (el.getAttribute('value') || '').trim();`,
      `        if (val) return true;`,
      `      }`,
      `      var titleAttr = (el.getAttribute('title') || '').trim();`,
      `      if (titleAttr) return true;`,
      `      return false;`,
      `    }`,
      `    function repairAccessibleNames() {`,
      `      try {`,
      `        var elements = document.querySelectorAll('button, [role="button"], a[href]');`,
      `        for (var i = 0; i < elements.length; i++) {`,
      `          var el = elements[i];`,
      `          if (hasAccessibleName(el)) continue;`,
      `          var isBtn = el.tagName === 'BUTTON' || el.getAttribute('role') === 'button';`,
      `          var docLang = (document.documentElement.lang || '').slice(0, 2).toLowerCase();`,
      `          var fallback = isBtn`,
      `            ? (docLang === 'ru' ? '\\u041a\\u043d\\u043e\\u043f\\u043a\\u0430' : (docLang === 'es' ? 'Bot\\u00f3n' : (docLang === 'zh' ? '\\u6309\\u94ae' : 'Button')))`,
      `            : (docLang === 'ru' ? '\\u0421\\u0441\\u044b\\u043b\\u043a\\u0430' : (docLang === 'es' ? 'Enlace' : (docLang === 'zh' ? '\\u94fe\\u63a5' : 'Link')));`,
      `          el.setAttribute('aria-label', fallback);`,
      `        }`,
      `      } catch (err) {}`,
      `    }`,
      `    repairAccessibleNames();`,
      ``,
      `    /* MutationObserver: throttle 500ms, disconnect after 30s */`,
      `    if (typeof window.MutationObserver !== 'undefined' && document.body) {`,
      `      var timer = null;`,
      `      var throttledRepair = function() {`,
      `        if (timer) return;`,
      `        timer = setTimeout(function() {`,
      `          timer = null;`,
      `          repairAccessibleNames();`,
      `        }, 500);`,
      `      };`,
      `      var observer = new MutationObserver(throttledRepair);`,
      `      observer.observe(document.body, { childList: true, subtree: true });`,
      `      setTimeout(function() {`,
      `        try { observer.disconnect(); } catch (e) {}`,
      `      }, 30000);`,
      `    }`,
      ``
    );
  }

  jsLines.push(
    `  }`,
    `  if (document.readyState === 'loading') {`,
    `    document.addEventListener('DOMContentLoaded', initAIfaFocus);`,
    `  } else {`,
    `    initAIfaFocus();`,
    `  }`,
    `})();`
  );

  const js = jsLines.join('\n');

  // ─── 3. HTML EMBED CODE ────────────────────────────────────────────────────
  const embedHtml = [
    `<!-- AIfaFocus 1-Click Accessibility Patch -->`,
    `<style>`,
    css.trim(),
    `</style>`,
    `<script>`,
    js.trim(),
    `</script>`,
    `<!-- End AIfaFocus Patch -->`,
  ].join('\n');

  const cssBytes = Buffer.byteLength(css, 'utf8');
  const jsBytes = Buffer.byteLength(js, 'utf8');
  const totalBytes = cssBytes + jsBytes;

  return {
    css,
    js,
    embedHtml,
    summary: {
      techniquesCount,
      fixedIssuesCount: techniquesCount,
      features,
      cssBytes,
      jsBytes,
      totalBytes,
    },
  };
}
