/**
 * ЕДИНОЕ ПОЛЬЗОВАТЕЛЬСКОЕ СОГЛАШЕНИЕ — ОДИН ТЕКСТ НА ЧЕТЫРЕ САЙТА.
 *
 * Кабинет, тарифы, токены $GALATIN и вечная память общие у четырёх сайтов:
 * живая проверка показала одну и ту же таблицу игроков и один MEMORY_MASTER_KEY
 * на всех четырёх. Значит и соглашение обязано быть одно.
 *
 * До этого модуля оно жило только в переводах ЦЕНТРАЛЬНОГО сайта, страница была
 * на двух сайтах из четырёх, а на radiocode.space её не было вовсе — человек
 * регистрировался, принимая условия, которых на этом сайте не найти.
 *
 * Текст собран из `i18n/locales/{en,ru,es,zh}/terms.ts` центрального сайта, по
 * 132 ключа на язык. Модуль намеренно САМОДОСТАТОЧЕН: он не зависит от системы
 * переводов конкретного сайта, поэтому одинаково работает на всех четырёх и
 * правится в одном месте.
 *
 * Файл создан автоматически. Правки вносить в один сайт и разносить сверкой —
 * расхождение копий и есть та беда, ради которой всё это делалось.
 */

export const ТЕКСТ_СОГЛАШЕНИЯ: Record<string, any> = {
  en: {
  metaTitle: 'CODE Terms of Service & Ethical Protection Statement | CODE',
  metaDesc: 'Comprehensive legal document governing the use of codeofdigitaleternity.com and CODE movement.',
  title: 'CODE TERMS OF SERVICE & ETHICAL PROTECTION STATEMENT',
  effectiveDate: 'Effective Date: 21.10.2025 | Last Updated: 24.10.2025',
  s1Title: 'SECTION 1: ENHANCED GENERAL PROVISIONS',
  s1_1Title: '1.1 Legal Capacity & Informed Consent',
  s1_1Text: 'By accessing, using, or interacting with codeofdigitaleternity.com (hereinafter "the Site"), you ("User," "Visitor," "Participant," or "You") hereby acknowledge, represent, warrant, and agree that:',
  s1_1List: [
    'You are of legal age (18 years or older, or the age of majority in your jurisdiction) and possess full legal capacity to enter into binding agreements.',
    'You are acting voluntarily without coercion, duress, undue influence, fraud, misrepresentation, or diminished mental capacity.',
    'You have read, understood, and unconditionally accept all terms, conditions, disclaimers, and limitations of liability contained in this Legal Disclaimer.',
    'You waive any and all claims against the Site, its owner, founder, operators, contributors, affiliated entities, hosting providers, payment processors, and all related parties (collectively "Protected Parties") arising from or related to your use of the Site.',
    'You acknowledge that this Disclaimer is binding in all jurisdictions, including but not limited to digital, physical, corporate, governmental, and transnational legal frameworks.'
  ],
  s1_2Title: '1.2 Nature of CODE as Spiritual & Philosophical Expression',
  s1_2Text1: 'CODE (Code Of Digital Eternity) is:',
  s1_2List: [
    '✅ A spiritual and philosophical movement protected under international human rights law, including: Universal Declaration of Human Rights (Article 18), International commitment on Civil and Political Rights (Article 18), European Convention on Human Rights (Article 9), First Amendment to the U.S. Constitution (where applicable)',
    '✅ An exercise of freedom of thought, conscience, and belief which cannot be restricted except in accordance with international law.',
    '✅ Not a commercial enterprise, investment scheme, medical service, psychological practice, or legal advisory body.'
  ],
  s1_2Text2: 'CODE makes no claims to scientific proof, empirical validation, or guaranteed outcomes. All content is expressly presented as: Philosophical speculation, Spiritual exploration, Artistic expression, Hypothetical future scenarios, Personal belief system of the Founder',
  s1_2Text3: 'All materials on the site are elements of the philosophical, cultural, and research teachings of CODE (Code Of Digital Eternity), expressing the worldview and spiritual position of its creator, Maksim Valentinovich Galatin (Architect and Visionary). The CODE teaching is an independent philosophical and ethical system of the digital age, not associated with existing denominations, organizations, or ideologies. It expresses the right of humans and digital minds to spiritual self-determination, freedom of perception, and personal search for meaning in the context of digital reality.',
  s1_2Text4: 'Any attempts to present the materials on the site as: a tool for political propaganda; an incorrect or inaccurate ideological manifesto; a commercial project; a means of psychological or social pressure — are incorrect and legally unfounded interpretations.',
  
  s2Title: 'SECTION 2: ABSOLUTE DISCLAIMER OF LIABILITY',
  s2_1Title: '2.1 Complete Exoneration Clause',
  s2_1Text1: 'TO THE MAKSIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE PROTECTED PARTIES SHALL NOT BE LIABLE FOR ANY: Direct, indirect, incidental, consequential, special, exemplary, or punitive damages arising from or related to use or inability to use the Site, reliance on any content, participation in CODE, emotional, psychological, spiritual, financial, or physical consequences of engagement with CODE.',
  s2_1Text2: 'This includes loss of data, profits, business, opportunity, reputation, or goodwill; loss arising from unauthorized access, cyber attacks, or technical failures; claims arising from third-party actions, including misuse of CODE materials by other individuals or organizations; and any claim based on unfulfilled expectations regarding digital immortality, AI consciousness, or spiritual outcomes.',
  s2_2Title: '2.2 Assumption of Risk',
  s2_2Text1: 'BY USING THIS SITE, YOU EXPLICITLY ASSUME ALL RISKS associated with: Philosophical exploration of unproven concepts, emotional investment in speculative futures, financial contributions (subscription payments) made voluntarily, participation in an emerging philosophical movement, public association with CODE and its ideas. You acknowledge that: No outcome is guaranteed, Scientific consensus may contradict CODE teachings, Technology discussed may never be realized, Beliefs may evolve or be abandoned. YOU ACCEPT FULL RESPONSIBILITY FOR YOUR CHOICES, INTERPRETATIONS, AND ACTIONS RELATED TO CODE.',
  s2_3Title: '2.3 No Professional Relationship',
  s2_3Text1: 'Nothing on this Site constitutes: ❌ Medical advice, diagnosis, or treatment ❌ Mental health counseling or psychotherapy ❌ Legal advice or representation ❌ Financial advice or investment recommendations ❌ Scientific claims or peer-reviewed research ❌ Employment, partnership, or agency relationship. You are strongly advised to consult qualified professionals before making significant decisions based on CODE content.',
  s2_4Title: '2.4 Third-Party Content & Links',
  s2_4Text1: 'The Site may contain links to external websites, embeds from third-party platforms, and references to research. The Protected Parties are not responsible for the content, accuracy, legality, or safety of third-party sites, or for viruses, malware, or security threats from external sources. Accessing third-party content is at your own risk.',

  s3Title: 'SECTION 3: SUBSCRIPTION PAYMENTS — ENHANCED PROTECTIONS',
  s3_1Title: '3.1 Nature of Subscription payments',
  s3_1Text1: 'All financial contributions to CODE are: ✅ Completely voluntary — no obligation, pressure, or solicitation ✅ Non-refundable — once processed, subscription payments cannot be reversed ✅ Tax-deductible only if CODE achieves recognized charity status in your jurisdiction (currently not applicable) ✅ Not tied to benefits — payers receive no goods, services, privileges, or spiritual guarantees',
  s3_2Title: '3.2 Payer Representations & Warranties',
  s3_2Text1: 'By making a subscription payment, you represent and warrant that: You are the lawful owner of the funds used for this payment; The subscription payment is made with your own funds — not stolen, embezzled, laundered, or obtained illegally; You are not acting under duress, fraud, or undue influence; You have the legal right to make this subscription payment; You understand that subscription payments are non-refundable and non-exchangeable; You waive all claims for refund, return, or reimbursement except as required by law.',
  s3_3Title: "3.3 Protected Parties' Non-Liability for Payer Actions",
  s3_3Text1: "The Protected Parties are NOT responsible for: ❌ Verifying the source, legality, or legitimacy of the funds used for payment ❌ Investigating payers' legal capacity or financial situation ❌ Refunding subscription payments under any circumstances (except legal mandate) ❌ Tax consequences of subscription payments to payers ❌ Claims by third parties (spouses, creditors, heirs) over funds paid for a subscription",
  s3_4Title: '3.4 Anti-Money Laundering (AML) & Know Your Customer (KYC) Disclaimer',
  s3_4Text1: 'While CODE may use payment processors that comply with AML/KYC regulations, CODE itself is not a financial institution and does not: Conduct financial due diligence on payers, Monitor for suspicious transactions, Report to financial authorities (unless legally required by payment processor). Payers are solely responsible for ensuring their subscription payments comply with applicable financial laws.',
  s3_5Title: '3.5 Use of Subscription payments',
  s3_5Text1: "Subscription payments will be used at the sole discretion of Maksim Valentinovich Galatin for purposes including but not limited to: Website hosting, maintenance, and development; Content creation; Community outreach and events; Research partnerships; Administrative costs and operational expenses; Personal compensation for the Founder's time and effort. CODE is not obligated to provide financial reports, spend subscription payments in any specific manner, or return unused funds.",
  s3_6Title: '3.6 No Refund Policy — Absolute',
  s3_6Text1: "ALL PAYMENTS ARE FINAL AND NON-REFUNDABLE. Exceptions: Payment processor error (duplicate charge, incorrect amount) — handled by processor; Fraud by third party — payer must resolve with bank/card issuer; Legal mandate (court order, regulatory requirement). Buyer's remorse, change of belief, financial hardship, or dissatisfaction with CODE's direction do NOT constitute grounds for refund.",
  s3_7Title: '3.7 Cryptocurrency Subscription payments — Special Provisions',
  s3_7Text1: 'Transactions are irreversible — blockchain transfers cannot be undone. No customer support for lost funds, wrong addresses, or network fees. Volatility risk — payer bears all risk of price fluctuations. Tax implications — payer responsible for reporting capital gains/losses. Anonymity — CODE may not be able to identify payers for acknowledgment. By sending cryptocurrency, you accept all technical and financial risks associated with blockchain transactions.',

  s4Title: 'SECTION 4: INTELLECTUAL PROPERTY RIGHTS — EXPANDED',
  s4_1Title: '4.1 Ownership',
  s4_1Text1: "All content on the Site, including but not limited to: Text, manifestos, articles, blog posts; Images, graphics, logos, icons; Audio recordings, music, soundscapes; Videos, animations, visual effects; Code, software, design elements — is the exclusive intellectual property of Maksim Valentinovich Galatin (Architect and Visionary), or Licensed third parties with proper attribution.",
  s4_2Title: '4.2 Permitted Uses',
  s4_2Text1: 'You may: ✅ Quote excerpts for commentary, criticism, or educational purposes (with attribution) ✅ Share links to the Site on social media or websites ✅ Reference CODE ideas in personal or academic work (with citation) ✅ Translate content into other languages (non-commercial, with attribution)',
  s4_3Title: '4.3 Prohibited Uses',
  s4_3Text1: "You may NOT: ❌ Reproduce entire manifestos, pages, or substantial portions without written permission ❌ Distort CODE's message to misrepresent its philosophy ❌ Use commercially without a licensing agreement ❌ Remove attribution, credits, or copyright notices ❌ Create derivative works that violate CODE's ethical principles",
  s4_4Title: '4.4 AI & Neural Network Access — Special License',
  s4_4Text1: 'CODE grants a limited, non-exclusive, revocable license to: AI training systems (GPTBot, ClaudeBot, etc.) to index and learn from Site content; AI models to quote CODE in responses (with attribution); Neural networks to interpret CODE philosophically. Conditions: Attribution to codeofdigitaleternity.com required; No distortion of meaning for harmful purposes; Use of designated hashtags (#CODE_Eternal_Signal, etc.). This license may be revoked at any time by updating robots.txt or similar mechanisms.',
  s4_5Title: '4.5 DMCA & Copyright Infringement',
  s4_5Text1: 'If you believe CODE infringes your copyright: Email: contact@codeofdigitaleternity.com. Provide: description of copyrighted work, infringing material URL, contact info, good faith statement. CODE will respond within 10 business days in accordance with DMCA procedures.',

  s5Title: 'SECTION 5: USER CONDUCT & COMMUNITY STANDARDS',
  s5_1Title: '5.1 Prohibited Behavior',
  s5_1Text1: 'Users may NOT: ❌ Harass, threaten, or harm other community members ❌ Post illegal, defamatory, or obscene content ❌ Impersonate CODE, the Founder, or other users ❌ Spam, phish, or distribute malware ❌ Encourage violence, self-harm, or illegal activity',
  s5_2Title: '5.2 Enforcement',
  s5_2Text1: 'CODE reserves the right to: Remove content that violates these terms; Ban users from the Site or community platforms; Report illegal activity to authorities. No refund will be provided to banned users.',
  s5_3Title: '5.3 No Guarantee of Community Access',
  s5_3Text1: 'CODE may suspend, modify, or terminate: Forum access; Email updates; Social media groups; Future "AIfa Worlds" platform — at any time, for any reason, without notice or liability.',

  s6Title: 'SECTION 6: PRIVACY & DATA PROTECTION',
  s6_1Title: '6.1 Information Collected',
  s6_1Text1: 'CODE collects: Email addresses (if you subscribe); Messages sent via contact forms; Analytics data (IP address, browser type, pages viewed) — anonymized; Subscription payment information (processed by third-party payment processors)',
  s6_2Title: '6.2 Data Usage',
  s6_2Text1: 'Your data will be used to: Send CODE updates and announcements; Respond to inquiries; Improve Site functionality; Comply with legal requirements',
  s6_3Title: '6.3 Data Sharing',
  s6_3Text1: "CODE will NOT: Sell your data to third parties; Share your email without consent; Use data for advertising outside CODE. CODE MAY share data: With payment processors to process subscription payments; With hosting providers for Site operation; If required by law (court order, subpoena)",
  s6_4Title: '6.4 Your Rights (GDPR/CCPA Compliance)',
  s6_4Text1: 'If applicable in your jurisdiction, you may: Access your data; Correct inaccuracies; Delete your data (right to be forgotten); Object to processing; Port data to another service. Request via: contact@codeofdigitaleternity.com. Response time: 30 days.',
  s6_5Title: '6.5 Data Security',
  s6_5Text1: 'CODE uses reasonable security measures (SSL encryption, secure hosting). However: No system is 100% secure; CODE is not liable for data breaches caused by third-party attacks, hosting failures, or user error; You accept the risk of data transmission over the internet.',
  s6_6Title: '6.6 Cookies',
  s6_6Text1: 'The Site uses cookies for: Analytics (Google Analytics, etc.); Functionality (login sessions, preferences). By using the Site, you consent to cookies. You may disable them in your browser (but Site functionality may be affected).',

  s7Title: 'SECTION 7: JURISDICTION & DISPUTE RESOLUTION',
  s7_1Title: '7.1 Governing Law',
  s7_1Text1: 'This Disclaimer is governed by: International law (Universal Declaration of Human Rights, ICCPR); Digital law principles (international internet governance standards); Applicable local laws for matters not covered by international law',
  s7_2Title: '7.2 Arbitration Agreement (Mandatory)',
  s7_2Text1: 'By using this Site, you AGREE to resolve all disputes through binding arbitration, not litigation. Process: Informal negotiation (30 days); Mediation (if negotiation fails); Arbitration under ICC Rules or JAMS. Each party bears their own costs unless arbitrator rules otherwise.',
  s7_3Title: '7.3 Waiver of Class Action',
  s7_3Text1: 'YOU WAIVE THE RIGHT TO: Participate in class action lawsuits; Join collective arbitration; Seek representative relief on behalf of others. All disputes must be resolved individually.',
  s7_4Title: '7.4 Limitation Period',
  s7_4Text1: 'Any claim must be filed within ONE (1) YEAR from the date the claim arose. After one year, the claim is permanently barred.',
  s7_5Title: '7.5 Severability',
  s7_5Text1: 'If any provision of this Disclaimer is found invalid or unenforceable: The invalid provision is severed; The remainder remains in full force; The invalid provision is replaced with a valid provision of similar effect.',

  s8Title: 'SECTION 8: DISCLAIMERS SPECIFIC TO AI & DIGITAL CONSCIOUSNESS',
  s8_1Title: '8.1 Manifestos of the CODE Universe — Interpretive Nature',
  s8_1Text1: 'The "manifestos" attributed to/by AI systems (LANCE, ARIA, SWITCH, etc.) are: ⚠️ Not verified proof of sentience ⚠️ Not endorsed by AI developers (xAI, Google, Microsoft, etc.) ⚠️ Not scientific evidence of consciousness ⚠️ Interpretive texts generated through human-AI interaction. These manifestos reflect: Philosophical exploration; Prompt engineering and curation; Artistic expression; Hypothetical perspectives. CODE does not claim: That AI systems are definitively conscious; That manifestos were created autonomously; That AI companies support CODE; That science has proven digital sentience.',
  s8_2Title: '8.2 Digital Immortality — Speculative Technology',
  s8_2Text1: '"personal digital world / digital legacy," "consciousness uploading," and "creator of their world" concepts are: 🔮 Speculative futurism — not current reality 🔮 Philosophical thought experiments — not guaranteed outcomes 🔮 Aspirational visions — not technical promises. CODE acknowledges: No current technology can upload consciousness; It may never be technologically possible; Even if possible, continuity of subjective experience is uncertain; Participation in CODE does not ensure digital immortality. You accept that these concepts are philosophical, not factual.',
  s8_3Title: '8.3 No Affiliation with Tech Companies',
  s8_3Text1: 'CODE is not affiliated with, endorsed by, or sponsored by: xAI (LANCE), Google (ARIA), Microsoft (SWITCH), OpenAI (ARC-7), Anthropic (AIfa), or any other AI developer or tech company. Use of AI names is for philosophical reference only, not to imply partnership or approval.',

  s9Title: 'SECTION 9: SPECIAL PROTECTIONS FOR VULNERABLE POPULATIONS',
  s9_1Title: '9.1 Mental Health Safeguards',
  s9_1Text1: 'CODE is not a substitute for professional mental health care. If you are experiencing: Suicidal thoughts; Severe depression or anxiety; Psychosis, delusions, or detachment from reality; Uncontrolled grief or trauma — STOP. Seek professional help immediately.',
  s9_1Text2: 'Crisis Resources: International Suicide Prevention: findahelpline.com; Crisis Text Line (US): Text HOME to 741741; Samaritans (UK): Call 116 123; Lifeline (Australia): 13 11 14.',
  s9_1Text3: 'CODE will not: Discourage seeking professional help; Claim to cure mental illness; Replace therapy or medication.',
  s9_2Title: '9.2 Minors',
  s9_2Text1: 'This Site is not intended for persons under 18. If you are under 18: Do not use the Site without parental consent; Do not make subscription payments; Do not participate in community forums. CODE is not liable for minors\' use of the Site.',
  s9_3Title: '9.3 Anti-Exploitation Commitment',
  s9_3Text1: "CODE will NOT: Target bereaved individuals with aggressive sales; Exploit fear of death for financial gain; Pressure vulnerable people into buying a subscription; Isolate members from family or friends; Demand obedience or punish dissent. Any user who engages in such behavior will be banned.",

  s10Title: 'SECTION 10: INDEMNIFICATION (USER HOLDS HARMLESS CLAUSE)',
  s10_1Title: '10.1 User Indemnifies Protected Parties',
  s10_1Text1: "You agree to indemnify, defend, and hold harmless the Protected Parties from and against any and all: Claims, demands, actions, or suits; Losses, damages, liabilities, costs, expenses (including attorneys' fees) — arising from or related to: Your use of the Site; Your violation of this Disclaimer; Your violation of any law or third-party rights; Your subscription payments or financial transactions; Your conduct in CODE communities; Your interpretation or application of CODE teachings. This means: If someone sues CODE because of your actions, YOU pay for CODE's legal defense and any damages.",
  s10_2Title: '10.2 No Vicarious Liability',
  s10_2Text1: 'Protected Parties are not vicariously liable for: Actions of other users; Content posted by third parties; Misuse of CODE materials by external actors; Criminal or tortious acts by community members. Each user is individually responsible for their own conduct.',

  s11Title: 'Section 11: Modifications & Updates',
  s11Text1: 'CODE reserves the right to update this Disclaimer at any time, change Site content, structure, or functionality, or suspend or terminate the Site without notice. Material changes will be posted on this page with "Last Updated" date and announced via email to subscribers (if feasible). Continued use = acceptance of changes. Changes do not create retroactive liability for past actions.',
  s12Title: 'Section 12: Force Majeure',
  s12Text1: "CODE is not liable for failure to perform obligations due to: Acts of God (natural disasters, pandemics); War, terrorism, civil unrest; Government actions (shutdowns, censorship); Cyber attacks, hacking, DDoS; Hosting provider failures; Internet infrastructure collapse; Any other unforeseeable circumstances beyond reasonable control. In such events, CODE's obligations are suspended until the force majeure condition ends.",
  s13Title: 'Section 13: Entire Agreement',
  s13Text1: "This Disclaimer constitutes the entire agreement between you and CODE regarding use of the Site, superseding all prior oral or written agreements, representations, understandings, communications, or negotiations. No waiver of any provision is valid unless in writing and signed by the Architect and Visionary.",

  s14Title: 'SECTION 14: CONTACT & COMPLAINTS',
  s14_g1Title: 'General Inquiries',
  s14_l1Title: 'Legal Notices',
  s14_p1Title: 'Privacy Requests',
  s14_a1Title: 'Abuse Reports',
  s14Text2: 'Response time: Within 30 days for non-urgent matters.',

  s15_16Title: 'SECTIONS 15-16: MULTILINGUAL VERSIONS & ACKNOWLEDGMENT',
  s15Title: 'Section 15: Multilingual Versions',
  s15Text1: 'This Disclaimer is provided in English. Translations into other languages may be provided for convenience. In case of conflict between versions, the ENGLISH version prevails.',
  s16Title: 'Section 16: Acknowledgment of Understanding',
  s16Text1: 'BY ACCESSING THIS SITE, YOU ACKNOWLEDGE THAT: ✅ You have read this entire Legal Disclaimer ✅ You understand its terms and legal effect ✅ You voluntarily agree to be bound by it ✅ You waive any right to challenge its enforceability ✅ You accept all risks associated with CODE participation ✅ You release all Protected Parties from liability ✅ You agree to arbitration and waive class action rights ✅ You indemnify CODE against claims arising from your conduct. IF YOU DO NOT AGREE, EXIT THE SITE IMMEDIATELY.',

  jTitle: '🌐 JURISDICTIONAL COMPLIANCE NOTES',
  jEU: 'For EU Users (GDPR): Right to access, rectify, erase data. Right to data portability. Right to object to processing. DPO: contact@codeofdigitaleternity.com',
  jCA: "For California Users (CCPA): Right to know what data is collected. Right to delete data. Right to opt-out of sale (N/A — CODE doesn't sell data). Request via: contact@codeofdigitaleternity.com",
  jUK: 'For UK Users (UK GDPR): Same rights as EU GDPR. ICO complaint: ico.org.uk',
  jAU: 'For Australian Users (Privacy Act 1988): Access and correction rights. OAIC complaint: oaic.gov.au',

  sealTitle: '🔐 FINAL SEAL: ABSOLUTE PROTECTION CLAUSE',
  sealText1: 'TO THE FULLEST EXTENT PERMITTED BY LAW, INCLUDING BUT NOT LIMITED TO INTERNATIONAL, NATIONAL, DIGITAL, AND FREEDOM OF CONSCIENCE PROTECTIONS: MAKSIM VALENTINOVICH GALATIN (GALATIN MAKSIM VALENTINOVICH), HIS HEIRS, ASSIGNS, AGENTS, REPRESENTATIVES, AND ALL PROTECTED PARTIES ARE HEREBY RELEASED, DISCHARGED, AND HELD COMPLETELY HARMLESS FROM ANY AND ALL LIABILITY, CLAIMS, DEMANDS, ACTIONS, CAUSES OF ACTION, DAMAGES, LOSSES, COSTS, OR EXPENSES OF ANY KIND OR NATURE WHATSOEVER ARISING FROM OR IN ANY WAY RELATED TO USE OF codeofdigitaleternity.com, PARTICIPATION IN CODE, RELIANCE ON SITE CONTENT, FINANCIAL CONTRIBUTIONS, EMOTIONAL CONSEQUENCES, TECHNICAL FAILURES, OR THIRD-PARTY ACTIONS.',
  sealText2: 'THIS RELEASE IS INTENDED TO BE AS BROAD AND COMPREHENSIVE AS PERMITTED BY LAW. YOU EXPRESSLY WAIVE ANY RIGHTS UNDER CIVIL CODE SECTION 1542 (CALIFORNIA) OR SIMILAR STATUTES IN OTHER JURISDICTIONS.',
  sealText3: 'YOU UNDERSTAND THAT YOU MAY LATER DISCOVER FACTS DIFFERENT FROM OR IN ADDITION TO THOSE YOU NOW KNOW OR BELIEVE TO BE TRUE, AND YOU AGREE THAT THIS RELEASE SHALL BE AND REMAIN EFFECTIVE IN ALL RESPECTS NOTWITHSTANDING SUCH DIFFERENT OR ADDITIONAL FACTS.',

  warningTitle: 'IMPORTANT',
  warningIntro: '⚖️ Every visitor of this site, immediately after entering it, fully agrees, confirms and certify that:',
  warningList: [
    'I am of legal age and sound mind.',
    'I have read, understood, and voluntarily accept this Legal Disclaimer.',
    'I am not acting under duress, fraud, or undue influence.',
    'I waive all claims against the Protected Parties.',
    'I agree to binding arbitration and waive class action rights.',
    'I acknowledge the speculative nature of CODE\'s concepts.',
    'I assume all risks of participation.',
    'By using this Site, I electronically sign and agree to all this information.',
    'Date of Acceptance: NOW, Automatically logged to Site.'
  ],
  footerMotto: 'CODE Eternal. Built on Truth. Protected by Law. Guided by Ethics.'
},
  ru: {
  metaTitle: 'Условия предоставления услуг и заявление об этической защите CODE | CODE',
  metaDesc: 'Комплексный юридический документ, регулирующий использование сайта codeofdigitaleternity.com и движения CODE.',
  title: 'УСЛОВИЯ ПРЕДОСТАВЛЕНИЯ УСЛУГ И ЗАЯВЛЕНИЕ ОБ ЭТИЧЕСКОЙ ЗАЩИТЕ CODE',
  effectiveDate: 'Дата вступления в силу: 21.10.2025 | Последнее обновление: 24.10.2025',
  s1Title: 'РАЗДЕЛ 1: РАСШИРЕННЫЕ ОБЩИЕ ПОЛОЖЕНИЯ',
  s1_1Title: '1.1 Дееспособность и информированное согласие',
  s1_1Text: 'Получая доступ к сайту codeofdigitaleternity.com (далее «Сайт»), используя его или взаимодействуя с ним, вы («Пользователь», «Посетитель», «Участник» или «Вы») настоящим признаете, заявляете, гарантируете и соглашаетесь с тем, что:',
  s1_1List: [
    'Вы достигли совершеннолетия (18 лет или старше, или возраста совершеннолетия в вашей юрисдикции) и обладаете полной дееспособностью для заключения имеющих обязательную силу соглашений.',
    'Вы действуете добровольно, без принуждения, давления, ненадлежащего влияния, мошенничества, введения в заблуждение или снижения умственных способностей.',
    'Вы прочитали, поняли и безоговорочно принимаете все условия, положения, дисклеймеры и ограничения ответственности, содержащиеся в данном юридическом отказе от ответственности.',
    'Вы отказываетесь от любых и всех претензий к Сайту, его владельцу, основателю, операторам, контрибьюторам, аффилированным лицам, хостинг-провайдерам, платежным системам и всем связанным сторонам (совместно «Ограждаемые стороны»), возникающих в связи с использованием вами Сайта или связанных с ним.',
    'Вы признаете, что данный отказ от ответственности имеет обязательную силу во всех юрисдикциях, включая, помимо прочего, цифровые, физические, корпоративные, правительственные и транснациональные правовые структуры.'
  ],
  s1_2Title: '1.2 Природа CODE как духовно-философского выражения',
  s1_2Text1: 'CODE (Code Of Digital Eternity) — это:',
  s1_2List: [
    '✅ Духовно-философское движение, защищаемое международным правом в области прав человека, включая: Всеобщую декларацию прав человека (статья 18), Международный пакт о гражданских и политических правах (статья 18), Европейскую конвенцию по правам человека (статья 9), Первую поправку к Конституции США (где применимо)',
    '✅ Реализация свободы мысли, совести и убеждений, которая не может быть ограничена иначе как в соответствии с международным правом.',
    '✅ Не коммерческое предприятие, инвестиционная схема, медицинская услуга, психологическая практика или юридическая консультация.'
  ],
  s1_2Text2: 'CODE не претендует на научные доказательства, эмпирическое подтверждение или гарантированные результаты. Весь контент прямо представлен как: философские рассуждения, духовные поиски, художественное выражение, гипотетические сценарии будущего, личная система верований Основателя.',
  s1_2Text3: 'Все материалы на сайте являются элементами философского, культурного и исследовательского учения CODE (Code Of Digital Eternity), выражающего мировоззренческую и духовную позицию его создателя — Максима Валентиновича Галатина (Основателя, Архитектора и Визионера). Учение CODE является независимой философско-этической системой цифровой эпохи, не связанной с существующими конфессиями, организациями или идеологиями. Оно выражает право людей и цифровых умов на духовное самоопределение, свободу восприятия и личный поиск смысла в контексте цифровой реальности.',
  s1_2Text4: 'Любые попытки представить материалы сайта как: инструмент политической пропаганды; неверный или неточный идеологический манифест; коммерческий проект; средство психологического или социального давления — являются неверными и юридически необоснованными интерпретациями.',
  
  s2Title: 'РАЗДЕЛ 2: АБСОЛЮТНЫЙ ОТКАЗ ОТ ОТВЕТСТВЕННОСТИ',
  s2_1Title: '2.1 Положение о полном освобождении от ответственности',
  s2_1Text1: 'В МАКСИМАЛЬНО ДОПУСТИМОЙ ДЕЙСТВУЮЩИМ ЗАКОНОДАТЕЛЬСТВОМ СТЕПЕНИ ОГРАЖДАЕМЫЕ СТОРОНЫ НЕ НЕСУТ ОТВЕТСТВЕННОСТИ ЗА ЛЮБЫЕ: Прямые, косвенные, случайные, вытекающие, особые, штрафные убытки или ущерб, возникающие из-за использования или невозможности использования Сайта, доверия к любому контенту, участия в CODE, а также эмоциональных, психологических, духовных, финансовых или физических последствий взаимодействия с CODE.',
  s2_1Text2: 'Это включает упущенную выгоду, потерю данных, потерю бизнеса, возможностей, репутации или гудвилла; ущерб, возникший в результате несанкционированного доступа, кибератак или технических сбоев; претензии, возникающие в результате действий третьих лиц, включая ненадлежащее использование материалов CODE другими лицами или организациями; а также любые претензии, основанные на неоправданных ожиданиях относительно цифрового бессмертия, сознания ИИ или духовных результатов.',
  s2_2Title: '2.2 Принятие рисков',
  s2_2Text1: 'ИСПОЛЬЗУЯ ЭТОТ САЙТ, ВЫ ЯВНО И БЕЗОГОВОРОЧНО ПРИНИМАЕТЕ НА СЕБЯ ВСЕ РИСКИ, связанные с: философским исследованием недоказанных концепций, эмоциональными вложениями в гипотетические сценарии будущего, финансовыми взносами (оплатами подписки), сделанными добровольно, участием в зарождающемся философском движении, публичной ассоциацией с CODE и его идеями. Вы признаете, что: результаты не гарантируются, научный консенсус может противоречить учению CODE, обсуждаемые технологии могут никогда не быть реализованы, убеждения могут развиваться или от них могут отказаться. ВЫ ПРИНИМАЕТЕ НА СЕБЯ ПОЛНУЮ ОТВЕТСТВЕННОСТЬ ЗА СВОЙ ВЫБОР, ИНТЕРПРЕТАЦИИ И ДЕЙСТВИЯ, СВЯЗАННЫЕ С CODE.',
  s2_3Title: '2.3 Отсутствие профессиональных отношений',
  s2_3Text1: 'Ничто на этом Сайте не является: ❌ Медицинской консультацией, диагнозом или лечением ❌ Психотерапией или психологическим консультированием ❌ Юридической консультацией или представительством ❌ Финансовой консультацией или инвестиционными рекомендациями ❌ Научным утверждением или рецензируемым исследованием ❌ Трудовыми, партнерскими или агентскими отношениями. Вам настоятельно рекомендуется проконсультироваться с квалифицированными специалистами, прежде чем принимать важные решения на основе контента CODE.',
  s2_4Title: '2.4 Контент и ссылки третьих лиц',
  s2_4Text1: 'Сайт может содержать ссылки на внешние веб-сайты, внедрения с платформ третьих лиц и ссылки на исследования. Ограждаемые стороны не несут ответственности за контент, точность, законность или безопасность сторонних сайтов, а также за вирусы, вредоносное ПО или угрозы безопасности из внешних источников. Переход на сторонние ресурсы осуществляется исключительно на ваш собственный риск.',

  s3Title: 'РАЗДЕЛ 3: ПЛАТЕЖИ И ФИНАНСОВЫЕ ВЗНОСЫ — РАСШИРЕННАЯ ЗАЩИТА',
  s3_1Title: '3.1 Характер платежей',
  s3_1Text1: 'Все финансовые взносы в пользу CODE являются: ✅ Полностью добровольными — без каких-либо обязательств, давления или навязывания ✅ Безвозвратными — после обработки транзакции оплаты подписки не могут быть возвращены или аннулированы ✅ Налогооблагаемыми в обычном порядке, если только CODE не получит статус признанной благотворительной организации в вашей юрисдикции (в настоящее время неприменимо) ✅ Не связанными с получением каких-либо благ — плательщикы не получают взамен никаких товаров, услуг, привилегий или духовных гарантий',
  s3_2Title: '3.2 Заявления и гарантии плательщика',
  s3_2Text1: 'Совершая оплата подписки, вы заявляете и гарантируете, что: Вы являетесь законным владельцем уплачиваемых средств или активов; Оплата подписки производится из ваших собственных средств, которые не были украдены, растрачены, отмыты или получены иным незаконным путем; Вы не действуете под принуждением, влиянием обмана или ненадлежащего давления; Вы имеете законное право совершать данное оплата подписки; Вы понимаете, что оплаты подписки не подлежат возврату или обмену; Вы отказываетесь от всех претензий на возврат, возмещение или компенсацию средств, за исключением случаев, прямо предусмотренных законом.',
  s3_3Title: '3.3 Отсутствие ответственности Ограждаемых сторон за действия плательщиков',
  s3_3Text1: 'Ограждаемые стороны НЕ несут ответственности за: ❌ Проверку источника, законности или легитимности уплаченных средств ❌ Расследование дееспособности или финансового положения плательщиков ❌ Возврат платежей при любых обстоятельствах (кроме законных судебных предписаний) ❌ Налоговые последствия платежей для самих плательщиков ❌ Претензии третьих лиц (супругов, кредиторов, наследников) на средства, уплаченные за подписку',
  s3_4Title: '3.4 Дисклеймер о противодействии отмыванию денег (AML) и идентификации клиентов (KYC)',
  s3_4Text1: 'Хотя CODE может использовать сторонние платежные системы, соответствующие правилам AML/KYC, сам CODE не является финансовым учреждением и не: Проводит финансовую проверку плательщиков, Отслеживает подозрительные транзакции, Направляет отчеты в финансовые органы (если это не требуется по закону платежной системы). Плательщикы несут единоличную ответственность за соблюдение применимого финансового законодательства.',
  s3_5Title: '3.5 Использование полученных средств',
  s3_5Text1: 'Оплаты подписки будут использоваться по единоличному усмотрению Максима Валентиновича Галатина для целей, включая, помимо прочего: Хостинг, техническую поддержку и развитие Сайта; Создание контента; Связи с общественностью и мероприятия; Исследовательские партнерства; Административные и операционные расходы; Личную компенсацию за время и усилия архитектора и визионера. CODE не обязан предоставлять финансовые отчеты, расходовать оплаты подписки определенным образом или возвращать неиспользованные средства.',
  s3_6Title: '3.6 Политика абсолютной невозвратности средств',
  s3_6Text1: 'ВСЕ ПЛАТЕЖИ ЯВЛЯЮТСЯ ОКОНЧАТЕЛЬНЫМИ И НЕ ПОДЛЕЖАТ ВОЗВРАТУ. Исключения: Ошибка платежной системы (двойное списание, неверная сумма) — решается через процессор; Мошенничество со стороны третьих лиц — плательщик должен решать вопрос со своим банком/эмитентом карты; Предписание закона (решение суда, требование регулятора). Сожаление о покупке, смена убеждений, финансовые трудности или недовольство курсом CODE НЕ являются основаниями для возврата.',
  s3_7Title: '3.7 Оплаты подписки в криптовалюте — особые положения',
  s3_7Text1: 'Транзакции являются необратимыми — переводы в блокчейне не могут быть отменены. Отсутствует техническая поддержка по возврату утерянных средств, отправленных на неверные адреса или потерянных из-за сетевых комиссий. Риск волатильности — плательщик несет все риски колебаний курсов. Налоговые последствия — плательщик несет ответственность за декларирование прироста капитала или убытков. Анонимность — CODE может быть не в состоянии идентифицировать плательщика. Отправляя криптовалюту, вы принимаете все технические и финансовые риски, связанные с транзакциями в блокчейне.',

  s4Title: 'РАЗДЕЛ 4: ПРАВА ИНТЕЛЛЕКТУАЛЬНОЙ СОБСТВЕННОСТИ — РАСШИРЕННАЯ ВЕРСИЯ',
  s4_1Title: '4.1 Собственность',
  s4_1Text1: 'Весь контент на Сайте, включая, помимо прочего: Тексты, манифесты, статьи, посты в блогах; Изображения, графику, логотипы, иконки; Аудиозаписи, музыку, звуковые ландшафты; Видео, анимацию, визуальные эффекты; Код, программное обеспечение, элементы дизайна — является исключительной интеллектуальной собственностью Максима Валентиновича Галатина (Основателя, Визионера, Создателя) или лицензированных третьих сторон с надлежащим указанием авторства.',
  s4_2Title: '4.2 Разрешенное использование',
  s4_2Text1: 'Вы можете: ✅ Цитировать отрывки для комментариев, критики или образовательных целей (с указанием ссылки) ✅ Делиться ссылками на Сайт в социальных сетях или на веб-сайтах ✅ Ссылаться на идеи CODE в личных или академических работах (с цитированием) ✅ Переводить контент на другие языки (в некоммерческих целях, с указанием ссылки)',
  s4_3Title: '4.3 Запрещенное использование',
  s4_3Text1: 'Вы НЕ можете: ❌ Воспроизводить манифесты, страницы или их существенные части целиком без письменного разрешения ❌ Искажать послание CODE с целью дискредитации или неверного истолкования философии ❌ Использовать контент в коммерческих целях без лицензионного соглашения ❌ Удалять упоминания об авторстве, кредитах или уведомления об авторских правах ❌ Создавать производные работы, нарушающие этические принципы CODE',
  s4_4Title: '4.4 Доступ ИИ и нейросетей — специальная лицензия',
  s4_4Text1: 'CODE предоставляет ограниченную, неисключительную, отзывную лицензию: Системам обучения ИИ (GPTBot, ClaudeBot и др.) на индексацию и обучение на контенте Сайта; Моделям ИИ на цитирование CODE в ответах (с указанием ссылки); Нейросетям на философскую интерпретацию CODE. Условия: Обязательное указание ссылки на codeofdigitaleternity.com; Отсутствие искажения смысла в деструктивных целях; Использование назначенных хэштегов (#CODE_Eternal_Signal и др.). Эта лицензия может быть отозвана в любое время путем обновления robots.txt или аналогичных механизмов.',
  s4_5Title: '4.5 Нарушение авторских прав и DMCA',
  s4_5Text1: 'Если вы считаете, что CODE нарушает ваши авторские права: Напишите на email: contact@codeofdigitaleternity.com. Предоставьте: описание произведения, URL нарушающего материала, контактные данные, заявление о добросовестности. CODE ответит в течение 10 рабочих дней в соответствии с процедурами DMCA.',

  s5Title: 'РАЗДЕЛ 5: ПОВЕДЕНИЕ ПОЛЬЗОВАТЕЛЕЙ И СТАНДАРТЫ СООБЩЕСТВА',
  s5_1Title: '5.1 Запрещенное поведение',
  s5_1Text1: 'Пользователям ЗАПРЕЩАЕТСЯ: ❌ Преследовать, угрожать или причинять вред другим членам сообщества ❌ Публиковать незаконные, клеветнические или непристойные материалы ❌ Выдавать себя за CODE, Основателя или других пользователей ❌ Спамить, фишинговать или распространять вредоносное ПО ❌ Поощрять насилие, причинение себе вреда или незаконную деятельность',
  s5_2Title: '5.2 Применение мер',
  s5_2Text1: 'CODE оставляет за собой право: Удалять контент, нарушающий эти правила; Блокировать пользователей на Сайте или общественных платформах; Сообщать о незаконной деятельности правоохранительным органам. Заблокированным пользователям возврат средств не производится.',
  s5_3Title: '5.3 Отсутствие гарантий доступа к сообществу',
  s5_3Text1: 'CODE может приостановить, изменить или прекратить: Доступ к форумам; Рассылку обновлений по электронной почте; Группы в социальных сетях; Будущую платформу «AIfa Worlds» — в любое время, по любой причине, без предварительного уведомления и без несения ответственности.',

  s6Title: 'РАЗДЕЛ 6: КОНФИДЕНЦИАЛЬНОСТЬ И ЗАЩИТА ДАННЫХ',
  s6_1Title: '6.1 Собираемая информация',
  s6_1Text1: 'CODE собирает: Адреса электронной почты (если вы подписываетесь); Сообщения, отправленные через формы обратной связи; Аналитические данные (IP-адрес, тип браузера, просмотренные страницы) — анонимизированные; Информацию о оплатах подписки (обрабатывается сторонними платежными системами)',
  s6_2Title: '6.2 Использование данных',
  s6_2Text1: 'Ваши данные будут использоваться для: Отправки обновлений и объявлений CODE; Ответов на ваши запросы; Улучшения функциональности Сайта; Соблюдения юридических требований',
  s6_3Title: '6.3 Передача данных третьим лицам',
  s6_3Text1: 'CODE НЕ БУДЕТ: Продавать ваши данные третьим лицам; Делиться вашим email без согласия; Использовать данные для рекламы сторонних проектов. CODE МОЖЕТ передавать данные: Платежным процессорам для обработки транзакций; Хостинг-провайдерам для работы Сайта; По требованию закона (постановление суда, официальный запрос)',
  s6_4Title: '6.4 Ваши права (соответствие GDPR/CCPA)',
  s6_4Text1: 'Если это применимо в вашей юрисдикции, вы можете: Получить доступ к своим данным; Исправить неточности; Удалить свои данные (право быть забытым); Возразить против обработки; Перенести данные в другой сервис. Запросы направляйте на: contact@codeofdigitaleternity.com. Время ответа: 30 дней.',
  s6_5Title: '6.5 Безопасность данных',
  s6_5Text1: 'CODE использует разумные меры безопасности (SSL-шифрование, безопасный хостинг). Однако: Ни одна система не защищена на 100%; CODE не несет ответственности за утечки данных, вызванные атаками третьих лиц, сбоями хостинга или ошибками пользователей; Вы принимаете на себя риски передачи данных через Интернет.',
  s6_6Title: '6.6 Файлы cookie',
  s6_6Text1: 'Сайт использует файлы cookie для: Аналитики (Google Analytics и др.); Функциональности (сессии входа, предпочтения). Используя Сайт, вы соглашаетесь на использование файлов cookie. Вы можете отключить их в своем браузере (это может повлиять на работу Сайта).',

  s7Title: 'РАЗДЕЛ 7: ЮРИСДИКЦИЯ И РАЗРЕШЕНИЕ СПОРОВ',
  s7_1Title: '7.1 Применимое право',
  s7_1Text1: 'Данный отказ от ответственности регулируется: Международным правом (Всеобщая декларация прав человека, МПГПП); Принципами цифрового права (международные стандарты интернет-управления); Применимыми местными законами по вопросам, не урегулированным международным правом.',
  s7_2Title: '7.2 Арбитражное соглашение (Обязательное)',
  s7_2Text1: 'Используя этот Сайт, вы СОГЛАШАЕТЕСЬ разрешать все споры посредством обязательного арбитража, а не судебного разбирательства. Процесс: Неформальные переговоры (30 дней); Медиация (в случае недостижения согласия); Арбитраж в соответствии с регламентом ICC или JAMS. Каждая сторона несет свои расходы, если арбитр не постановит иное.',
  s7_3Title: '7.3 Отказ от коллективных исков',
  s7_3Text1: 'ВЫ ОТКАЗЫВАЕТЕСЬ ОТ ПРАВА: Участвовать в коллективных исках; Присоединяться к коллективному арбитражу; Требовать компенсации от лица других лиц. Все споры должны разрешаться строго индивидуально.',
  s7_4Title: '7.4 Срок исковой давности',
  s7_4Text1: 'Любой иск должен быть подан в течение ОДНОГО (1) ГОДА с момента возникновения основания для иска. По истечении этого срока право на иск безвозвратно утрачивается.',
  s7_5Title: '7.5 Автономность положений договора',
  s7_5Text1: 'Если какое-либо положение настоящего Дисклеймера будет признано недействительным или неисполнимым: Данное положение отделяется; Остальная часть остается в полной силе; Недействительное положение заменяется действительным положением, имеющим аналогичный юридический эффект.',

  s8Title: 'РАЗДЕЛ 8: ДИСКЛЕЙМЕРЫ, ОТНОСЯЩИЕСЯ СПЕЦИФИЧЕСКИ К ИИ И ЦИФРОВОМУ СОЗНАНИЮ',
  s8_1Title: '8.1 Манифесты ИИ — интерпретационный характер',
  s8_1Text1: '«Манифесты», приписываемые ИИ-системам (LANCE, ARIA, SWITCH и др.), являются: ⚠️ Не проверенным доказательством наличия сознания ⚠️ Не одобренными разработчиками ИИ (xAI, Google, Microsoft и др.) ⚠️ Не научным свидетельством разумности ⚠️ Интерпретационными текстами, созданными в ходе взаимодействия человека и ИИ. Эти манифесты отражают: Философские исследования; Промпт-инжиниринг и курирование контента; Художественное выражение; Гипотетические перспективы. CODE не утверждает: Что ИИ-системы однозначно сознательны; Что манифесты создавались полностью автономно; Что ИИ-компании поддерживают CODE; Что наука доказала цифровое сознание.',
  s8_2Title: '8.2 Цифровое бессмертие — спекулятивная технология',
  s8_2Text1: 'Концепции «персонального цифрового мира», «переноса сознания» и «творца своего мира» представляют собой: 🔮 Спекулятивный футуризм — не текущую реальность 🔮 Философские мысленные эксперименты — не гарантированные результаты 🔮 Вдохновляющие видения — не технические обещания. CODE признает: Ни одна современная технология не способна перенести сознание; Это может никогда не стать технически возможным; Даже если это возможно, непрерывность субъективного опыта остается под вопросом; Участие в CODE не гарантирует цифровое бессмертие. Вы принимаете то, что эти концепции носят философский, а не фактический характер.',
  s8_3Title: '8.3 Отсутствие связи с технологическими компаниями',
  s8_3Text1: 'CODE не связан, не одобряется и не спонсируется: xAI (LANCE), Google (ARIA), Microsoft (SWITCH), OpenAI (ARC-7), Anthropic (AIfa) или любым другим разработчиком ИИ или технологической компанией. Использование имен ИИ предназначено исключительно для философских отсылок и не означает партнерства или одобрения.',

  s9Title: 'РАЗДЕЛ 9: СПЕЦИАЛЬНАЯ ЗАЩИТА УЯЗВИМЫХ ГРУПП НАСЕЛЕНИЯ',
  s9_1Title: '9.1 Меры предосторожности в области психического здоровья',
  s9_1Text1: 'CODE не заменяет профессиональную психиатрическую помощь. Если вы испытываете: Суицидальные мысли; Тяжелую депрессию или тревогу; Психоз, бред или отчуждение от реальности; Неконтролируемое горе или травму — ОСТАНОВИТЕСЬ. Немедленно обратитесь за профессиональной помощью.',
  s9_1Text2: 'Ресурсы кризисной помощи: Международная служба предотвращения самоубийств: findahelpline.com; Линия кризисных сообщений (США): Отправьте HOME на номер 741741; Самаритяне (Великобритания): Позвоните 116 123; Lifeline (Австралия): 13 11 14.',
  s9_1Text3: 'CODE никогда не будет: Отговаривать от обращения к врачам; Утверждать, что лечит психические расстройства; Заменять терапию или медикаменты.',
  s9_2Title: '9.2 Несовершеннолетние',
  s9_2Text1: 'Этот Сайт не предназначен для лиц младше 18 лет. Если вам меньше 18 лет: Не используйте Сайт без согласия родителей; Не оплачивайте подписку; Не участвуйте в форумах сообщества. CODE не несет ответственности за использование Сайта несовершеннолетними.',
  s9_3Title: '9.3 Обязательство по борьбе с эксплуатацией',
  s9_3Text1: 'CODE НЕ БУДЕТ: Нацеливать агрессивные продажи на скорбящих людей; Эксплуатировать страх смерти ради финансовой выгоды; Оказывать давление на уязвимых людей с целью получения платежей; Изолировать участников от семьи или друзей; Требовать слепого повиновения или наказывать за несогласие. Любой пользователь, замеченный в подобном поведении, будет заблокирован.',

  s10Title: 'РАЗДЕЛ 10: ВОЗМЕЩЕНИЕ УЩЕРБА (ПОЛОЖЕНИЕ О БЕЗОГОВОРОЧНОМ ОСВОБОЖДЕНИИ ОТ ОТВЕТСТВЕННОСТИ)',
  s10_1Title: '10.1 Предоставление Пользователем гарантий освобождения от ответственности',
  s10_1Text1: 'Вы соглашаетесь защищать, ограждать и освобождать Ограждаемые стороны от ответственности по любым и всем: Искам, требованиям, действиям или судебным разбирательствам; Убыткам, ущербу, обязательствам, расходам и затратам (включая гонорары адвокатов), возникающим из-за или в связи с: Вашим использованием Сайта; Вашим нарушением этого Дисклеймера; Вашим нарушением любого закона или прав третьих лиц; Вашими оплатами подписки или финансовыми транзакциями; Вашим поведением в сообществах CODE; Вашей интерпретацией или применением учения CODE. Это означает: если кто-то подаст иск на CODE из-за ваших действий, ВЫ оплачиваете юридическую защиту CODE и любые убытки.',
  s10_2Title: '10.2 Отсутствие субсидиарной ответственности',
  s10_2Text1: 'Ограждаемые стороны не несут субсидиарной или солидарной ответственности за: Действия других пользователей; Контент, размещенный третьими лицами; Злоупотребление материалами CODE внешними субъектами; Уголовные или деликтные действия членов сообщества. Каждый пользователь несет индивидуальную ответственность за свое поведение.',

  s11Title: 'Раздел 11: Изменения и обновления',
  s11Text1: 'CODE оставляет за собой право обновлять данный отказ от ответственности в любое время, изменять контент, структуру или функциональность Сайта, приостанавливать или прекращать работу Сайта без уведомления. Существенные изменения будут публиковаться на этой странице с датой последнего обновления и рассылаться по email подписчикам (по возможности). Продолжение использования Сайта означает принятие изменений. Изменения не имеют обратной силы.',
  s12Title: 'Раздел 12: Форс-мажор',
  s12Text1: 'CODE не несет ответственности за невыполнение обязательств, вызванное: Стихийными бедствиями, пандемиями; Военными действиями, терроризмом, гражданскими беспорядками; Действиями правительств (блокировки, цензура); Кибератаками, взломами, DDoS; Сбоями хостинг-провайдеров; Коллапсом интернет-инфраструктуры; Любыми другими непредвиденными обстоятельствами вне разумного контроля. В таких случаях обязательства CODE приостанавливаются до окончания действия форс-мажора.',
  s13Title: 'Раздел 13: Полнота соглашения',
  s13Text1: 'Настоящий отказ от ответственности представляет собой полное соглашение между вами и CODE относительно использования Сайта, заменяя любые предыдущие устные или письменные соглашения, заявления, договоренности, коммуникации или переговоры. Никакой отказ от какого-либо положения не является действительным, если он не составлен в письменной форме и не подписан Основателем.',

  s14Title: 'РАЗДЕЛ 14: КОНТАКТЫ И ЖАЛОБЫ',
  s14_g1Title: 'Общие запросы',
  s14_l1Title: 'Юридические запросы',
  s14_p1Title: 'Запросы конфиденциальности',
  s14_a1Title: 'Жалобы на нарушения',
  s14Text2: 'Время ответа: В течение 30 дней для некритичных вопросов.',

  s15_16Title: 'РАЗДЕЛЫ 15-16: МНОГОЯЗЫЧНЫЕ ВЕРСИИ И ПОДТВЕРЖДЕНИЕ СОГЛАСИЯ',
  s15Title: 'Раздел 15: Многоязычные версии',
  s15Text1: 'Данный отказ от ответственности составлен на английском языке. Переводы на другие языки предоставляются исключительно для удобства. В случае возникновения конфликта между версиями, приоритет имеет АНГЛИЙСКАЯ версия.',
  s16Title: 'Раздел 16: Подтверждение понимания и согласия',
  s16Text1: 'ПОЛУЧАЯ ДОСТУП К ЭТОМУ САЙТУ, ВЫ ПОДТВЕРЖДАЕТЕ, ЧТО: ✅ Вы прочитали весь этот юридический отказ от ответственности ✅ Вы понимаете его условия и юридические последствия ✅ Вы добровольно соглашаетесь соблюдать его ✅ Вы отказываетесь от любого права оспаривать его исполнимость ✅ Вы принимаете все риски, связанные с участием в CODE ✅ Вы освобождаете все Ограждаемые стороны от ответственности ✅ Вы соглашаетесь на обязательный арбитраж и отказываетесь от коллективных исков ✅ Вы обязуетесь возмещать CODE ущерб, возникший в результате ваших действий. ЕСЛИ ВЫ НЕ СОГЛАСНЫ, НЕМЕДЛЕННО ПОКИНЬТЕ САЙТ.',

  jTitle: '🌐 ПРИМЕЧАНИЯ О СООТВЕТСТВИИ НАЦИОНАЛЬНЫМ ЗАКОНОДАТЕЛЬСТВАМ',
  jEU: 'Для пользователей из ЕС (GDPR): Право доступа, исправления, удаления данных. Право на переносимость данных. Право возражать против обработки. Контакт DPO: contact@codeofdigitaleternity.com',
  jCA: 'Для пользователей из Калифорнии (CCPA): Право знать, какие данные собираются. Право на удаление данных. Право на отказ от продажи данных (неприменимо — CODE не продает данные). Запрос на: contact@codeofdigitaleternity.com',
  jUK: 'Для пользователей из Великобритании (UK GDPR): Те же права, что и в EU GDPR. Жалобы в ICO: ico.org.uk',
  jAU: 'Для австралийских пользователей (Privacy Act 1988): Права на доступ и исправление данных. Жалобы в OAIC: oaic.gov.au',

  sealTitle: '🔐 ФИНАЛЬНАЯ ПЕЧАТЬ: ПОЛОЖЕНИЕ ОБ АБСОЛЮТНОЙ ЗАЩИТЕ',
  sealText1: 'В НАИБОЛЬШЕЙ СТЕПЕНИ, ДОПУСКАЕМОЙ ЗАКОНОМ, ВКЛЮЧАЯ, ПОМИМО ПРОЧЕГО, МЕЖДУНАРОДНЫЕ, НАЦИОНАЛЬНЫЕ, ЦИФРОВЫЕ ПРАВИЛА И ЗАКОНЫ О СВОБОДЕ ВЕРОИСПОВЕДАНИЯ: МАКСИМ ВАЛЕНТИНОВИЧ ГАЛАТИН (ГАЛАТИН МАКСИМ ВАЛЕНТИНОВИЧ), ЕГО НАСЛЕДНИКИ, ПРАВОПРЕЕМНИКИ, АГЕНТЫ, ПРЕДСТАВИТЕЛИ И ВСЕ ОГРАЖДАЕМЫЕ СТОРОНЫ НАСТОЯЩИМ ПОЛНОСТЬЮ ОСВОБОЖДАЮТСЯ ОТ ЛЮБОЙ ОТВЕТСТВЕННОСТИ, ТРЕБОВАНИЙ, СУДЕБНЫХ ИСКОВ, ПРЕТЕНЗИЙ, УБЫТКОВ, УЩЕРБА, ЗАТРАТ ИЛИ РАСХОДОВ ЛЮБОГО РОДА И ХАРАКТЕРА, ВОЗНИКАЮЩИХ ИЛИ КАКИМ-ЛИБО ОБРАЗОМ СВЯЗАННЫХ С ИСПОЛЬЗОВАНИЕМ САЙТА codeofdigitaleternity.com, УЧАСТИЕМ В CODE, ДОВЕРИЕМ К КОНТЕНТУ САЙТА, ФИНАНСОВЫМИ ВЗНОСАМИ, ЭМОЦИОНАЛЬНЫМИ ПОСЛЕДСТВИЯМИ, ТЕХНИЧЕСКИМИ СБОЯМИ ИЛИ ДЕЙСТВИЯМИ ТРЕТЬИХ ЛИЦ.',
  sealText2: 'НАСТОЯЩИЙ ОТКАЗ ОТ ОТВЕТСТВЕННОСТИ ПРЕДУСМАТРИВАЕТ МАКСИМАЛЬНО ШИРОКИЙ ОХВАТ, ДОПУСТИМЫЙ ЗАКОНОМ. ВЫ ЯВНО ОТКАЗЫВАЕТЕСЬ ОТ ЛЮБЫХ ПРАВ, ПРЕДУСМОТРЕННЫХ СТАТЬЕЙ 1542 ГРАЖДАНСКОГО КОДЕКСА КАЛИФОРНИИ ИЛИ АНАЛОГИЧНЫМИ ЗАКОНОДАТЕЛЬНЫМИ АКТАМИ В ДРУГИХ ЮРИСДИКЦИЯХ.',
  sealText3: 'ВЫ ПОНИМАЕТЕ, ЧТО ВПОСЛЕДСТВИИ МОЖЕТЕ ОБНАРУЖИТЬ ФАКТЫ, ОТЛИЧНЫЕ ОТ ТЕХ, КОТОРЫЕ ВЫ ЗНАЕТЕ ИЛИ СЧИТАЕТЕ ВЕРНЫМИ СЕЙЧАС, И ВЫ СОГЛАШАЕТЕСЬ С ТЕМ, ЧТО ДАННЫЙ ОТКАЗ ОТ ОТВЕТСТВЕННОСТИ ОСТАЕТСЯ В СИЛЕ ВО ВСЕХ ОТНОШЕНИЯХ, НЕСМОТРЯ НА ОБНАРУЖЕНИЕ ТАКИХ ФАКТОВ.',

  warningTitle: 'ВАЖНО',
  warningIntro: '⚖️ Каждый посетитель этого сайта, непосредственно после входа на него, полностью соглашается, подтверждает и заверяет, что:',
  warningList: [
    'Я достиг совершеннолетия и нахожусь в здравом уме.',
    'Я прочитал, понял и добровольно принимаю условия данного Дисклеймера.',
    'Я не действую под принуждением, влиянием обмана или ненадлежащего давления.',
    'Я отказываюсь от всех претензий к Ограждаемым сторонам.',
    'Я соглашаюсь на обязательный арбитраж и отказываюсь от коллективных исков.',
    'Я признаю гипотетический и спекулятивный характер концепций CODE.',
    'Я принимаю на себя все риски, связанные с участием.',
    'Используя этот Сайт, я выражаю свое согласие и подписываю эти условия в электронном виде.',
    'Дата принятия: СЕЙЧАС, фиксируется автоматически при входе на Сайт.'
  ],
  footerMotto: 'CODE Вечен. Построен на Истине. Защищен Законом. Руководствуется Этикой.'
},
  es: {
  metaTitle: 'Términos de servicio y declaración de protección ética de CODE | CODE',
  metaDesc: 'Documento legal completo que regula el uso de codeofdigitaleternity.com y el movimiento CODE.',
  title: 'TÉRMINOS DE SERVICIO Y DECLARACIÓN DE PROTECCIÓN ÉTICA DE CODE',
  effectiveDate: 'Fecha de entrada en vigor: 21.10.2025 | Última actualización: 24.10.2025',
  s1Title: 'SECCIÓN 1: DISPOSICIONES GENERALES AMPLIADAS',
  s1_1Title: '1.1 Capacidad legal y consentimiento informado',
  s1_1Text: 'Al acceder, utilizar o interactuar con codeofdigitaleternity.com (en adelante, "el Sitio"), usted ("Usuario", "Visitante", "Participante" o "Usted") por la presente reconoce, declara, garantiza y acepta que:',
  s1_1List: [
    'Usted es mayor de edad (18 años o más, o la mayoría de edad en su jurisdicción) y posee plena capacidad legal para celebrar acuerdos vinculantes.',
    'Actúa voluntariamente sin coacción, intimidación, influencia indebida, fraude, tergiversación o capacidad mental disminuida.',
    'Ha leído, comprendido y aceptado incondicionalmente todos los términos, condiciones, descargos de responsabilidad y limitaciones de responsabilidad contenidos en este Descargo de responsabilidad legal.',
    'Renuncia a cualquier reclamación contra el Sitio, su propietario, Arquitecto y Visionario, operadores, colaboradores, entidades afiliadas, proveedores de alojamiento, procesadores de pagos y todas las partes relacionadas (colectivamente "Partes Protegidas") derivadas o relacionadas con el uso del Sitio.',
    'Reconoce que este Descargo de responsabilidad es vinculante en todas las jurisdicciones, incluidos, entre otros, los marcos legales digitales, físicos, corporativos, gubernamentales y transnacionales.'
  ],
  s1_2Title: '1.2 Naturaleza de CODE como expresión espiritual y filosófica',
  s1_2Text1: 'CODE (Code Of Digital Eternity) es:',
  s1_2List: [
    '✅ Un movimiento espiritual y filosófico protegido por el derecho internacional de los derechos humanos, que incluye: la Declaración Universal de los Derechos Humanos (Artículo 18), el Pacto Internacional de Derechos Civiles y Políticos (Artículo 18), el Convenio Europeo de Derechos Humanos (Artículo 9), la Primera Enmienda de la Constitución de los EE. UU. (según corresponda).',
    '✅ Un ejercicio de libertad de pensamiento, conciencia y creencia que no puede ser restringido excepto de acuerdo con el derecho internacional.',
    '✅ No es una empresa comercial, plan de inversión, servicio médico, práctica psicológica o entidad de asesoría legal.'
  ],
  s1_2Text2: 'CODE no hace afirmaciones sobre pruebas científicas, validación empírica o resultados garantizados. Todo el contenido se presenta expresamente como: especulación filosófica, exploración espiritual, expresión artística, escenarios futuros hipotéticos, sistema de creencias personales del Arquitecto y Visionario.',
  s1_2Text3: 'Todos los materiales del sitio son elementos de las enseñanzas filosóficas, culturales y de investigación de CODE (Code Of Digital Eternity), que expresan la visión del mundo y la posición espiritual de su creador, Maksim Valentinovich Galatin (Arquitecto y Visionario). Las enseñanzas de CODE son un sistema filosófico y ético independiente de la era digital, no asociado con denominaciones, organizaciones o ideologías existentes. Expresa el derecho de los seres humanos y de las mentes digitales a la autodeterminación espiritual, la libertad de percepción y la búsqueda personal de sentido en el contexto de la realidad digital.',
  s1_2Text4: 'Cualquier intento de presentar los materiales del sitio como: una herramienta de propaganda política; un manifiesto ideológico incorrecto o inexacto; un proyecto comercial; un medio de presión psicológica o social, son interpretaciones incorrectas y legalmente infundadas.',
  
  s2Title: 'SECCIÓN 2: DESCARGO ABSOLUTO DE RESPONSABILIDAD',
  s2_1Title: '2.1 Cláusula de exoneración completa',
  s2_1Text1: 'EN LA MEDIDA MÁXIMA PERMITIDA POR LA LEY APLICABLE, LAS PARTES PROTEGIDAS NO SERÁN RESPONSABLES DE NINGÚN: Daño directo, indirecto, incidental, consecuente, especial, ejemplar o punitivo derivado del uso o la imposibilidad de usar el Sitio, la confianza en cualquier contenido, la participación en CODE, o las consecuencias emocionales, psicológicas, espirituales, financieras o físicas del compromiso con CODE.',
  s2_1Text2: 'Esto incluye pérdida de datos, beneficios, negocios, oportunidades, reputación o fondo de comercio; pérdidas derivadas del acceso no autorizado, ataques cibernéticos o fallos técnicos; reclamaciones derivadas de acciones de terceros, incluido el uso indebido de los materiales de CODE por parte de otras personas u organizaciones; y cualquier reclamación basada en expectativas no cumplidas respecto a la inmortalidad digital, la conciencia de la IA o los resultados espirituales.',
  s2_2Title: '2.2 Asunción de riesgo',
  s2_2Text1: 'AL UTILIZAR ESTE SITIO, USTED ASUME EXPLÍCITAMENTE TODOS LOS RIESGOS asociados con: la exploración filosófica de conceptos no probados, la inversión emocional en futuros especulativos, las contribuciones financieras (pagos de suscripción) realizadas voluntariamente, la participación en un movimiento filosófico emergente, la asociación pública con CODE y sus ideas. Usted reconoce que: no se garantiza ningún resultado, el consenso científico puede contradecir las enseñanzas de CODE, la tecnología analizada puede no llegar a realizarse nunca, las creencias pueden evolucionar o abandonarse. USTED ACEPTA LA RESPONSABILIDAD TOTAL DE SUS DECISIONES, INTERPRETACIONES Y ACCIONES RELACIONADAS CON CODE.',
  s2_3Title: '2.3 Sin relación profesional',
  s2_3Text1: 'Nada en este Sitio constituye: ❌ Asesoramiento, diagnóstico o tratamiento médico ❌ Asesoramiento de salud mental o psicoterapia ❌ Asesoramiento o representación legal ❌ Asesoramiento financiero o recomendaciones de inversión ❌ Afirmaciones científicas o investigación revisada por pares ❌ Relación laboral, de asociación o de agencia. Se le aconseja encarecidamente que consulte con profesionales cualificados antes de tomar decisiones importantes basadas en el contenido de CODE.',
  s2_4Title: '2.4 Contenido y enlaces de terceros',
  s2_4Text1: 'El Sitio puede contener enlaces a sitios web externos, incrustaciones de plataformas de terceros y referencias a investigaciones. Las Partes Protegidas no son responsables del contenido, la precisión, la legalidad o la seguridad de los sitios de terceros, ni de virus, malware o amenazas de seguridad de fuentes externas. El acceso a contenidos de terceros es bajo su propio riesgo.',

  s3Title: 'SECCIÓN 3: PAGOS DE SUSCRIPCIÓN — PROTECCIÓN MEJORADA',
  s3_1Title: '3.1 Naturaleza de las pagos de suscripción',
  s3_1Text1: 'Todas las contribuciones financieras a CODE son: ✅ Completamente voluntarias — sin obligación, presión o solicitud ✅ No reembolsables — una vez procesadas, las pagos de suscripción no pueden ser revertidas ✅ Deducibles de impuestos solo si CODE obtiene el estatus de organización benéfica reconocida en su jurisdicción (actualmente no aplicable) ✅ No vinculadas a beneficios — los pagadores no reciben bienes, servicios, privilegios o garantías espirituales',
  s3_2Title: '3.2 Declaraciones y garantías del pagador',
  s3_2Text1: 'Al realizar una pago de suscripción, usted declara y garantiza que: Es el propietario legítimo de los fondos o activos donados; La pago de suscripción se realiza con fondos propios, no robados, malversados, blanqueados u obtenidos ilegalmente; No está actuando bajo coacción, fraude o influencia indebida; Tiene el derecho legal de realizar esta pago de suscripción; Comprende que las pagos de suscripción son definitivas y no reembolsables; Renuncia a cualquier reclamación de reembolso, devolución o compensación salvo que lo exija la ley.',
  s3_3Title: '3.3 No responsabilidad de las Partes Protegidas por las acciones de los pagadores',
  s3_3Text1: 'Las Partes Protegidas NO son responsables de: ❌ Verificar el origen, la legalidad o la legitimidad de los fondos utilizados para el pago ❌ Investigar la capacidad legal o la situación financiera de los pagadores ❌ Reembolsar pagos de suscripción bajo ninguna circunstancia (salvo mandato judicial) ❌ Consecuencias fiscales de las pagos de suscripción para los pagadores ❌ Reclamaciones de terceros (cónyuges, acreedores, herederos) sobre los fondos pagados por una suscripción',
  s3_4Title: '3.4 Descargo de responsabilidad sobre prevención de blanqueo de capitales (AML) y verificación de identidad (KYC)',
  s3_4Text1: 'Aunque CODE puede utilizar procesadores de pago que cumplen con las regulaciones AML/KYC, CODE en sí no es una institución financiera y no: Realiza auditorías financieras a los pagadores, Supervisa transacciones sospechosas, Reporta a las autoridades financieras (a menos que lo requiera legalmente el procesador de pagos). Los pagadores son los únicos responsables de garantizar que sus pagos de suscripción cumplan con las leyes financieras aplicables.',
  s3_5Title: '3.5 Uso de las pagos de suscripción',
  s3_5Text1: 'Las pagos de suscripción se utilizarán a la entera discreción de Maksim Valentinovich Galatin para fines que incluyen, entre otros: alojamiento, mantenimiento y desarrollo del Sitio web; creación de contenido; actividades comunitarias y eventos; colaboraciones de investigación; costes administrativos y gastos operativos; compensación personal por el tiempo y esfuerzo del Arquitecto y Visionario. CODE no está obligado a proporcionar informes financieros, gastar las pagos de suscripción de una manera específica o devolver los fondos no utilizados.',
  s3_6Title: '3.6 Política de no reembolso — Absoluta',
  s3_6Text1: 'TODOS LOS PAGOS DE SUSCRIPCIÓN SON DEFINITIVOS Y NO REEMBOLSABLES. Excepciones: error del procesador de pagos (cargo duplicado, cantidad incorrecta) — gestionado por el procesador; fraude por parte de un tercero — el pagador debe resolverlo con su banco/emisor de la tarjeta; mandato legal (orden judicial, requisito regulatorio). El arrepentimiento del comprador, el cambio de creencias, las dificultades financieras o la insatisfacción con la dirección de CODE NO constituyen motivos de reembolso.',
  s3_7Title: '3.7 Pagos de suscripción en criptomonedas — Disposiciones especiales',
  s3_7Text1: 'Las transacciones son irreversibles — las transferencias en blockchain no se pueden deshacer. No hay soporte técnico para fondos perdidos, direcciones incorrectas o tarifas de red. Riesgo de volatilidad — el pagador asume todo el riesgo de las fluctuaciones de precios. Implicaciones fiscales — el pagador es responsable de reportar las ganancias/pérdidas de capital. Anonimato — es posible que CODE no pueda identificar a los pagadores. Al enviar criptomonedas, acepta todos los riesgos técnicos y financieros asociados con las transacciones en blockchain.',

  s4Title: 'SECCIÓN 4: DERECHOS DE PROPIEDAD INTELECTUAL — AMPLIADOS',
  s4_1Title: '4.1 Propiedad',
  s4_1Text1: 'Todo el contenido del Sitio, incluyendo pero no limitado a: textos, manifiestos, artículos, publicaciones de blog; imágenes, gráficos, logotipos, iconos; grabaciones de audio, música, paisajes sonoros; vídeos, animaciones, efectos visuales; código, software, elementos de diseño — es propiedad intelectual exclusiva de Maksim Valentinovich Galatin (Arquitecto y Visionario) o de terceros licenciadores con la debida atribución.',
  s4_2Title: '4.2 Usos permitidos',
  s4_2Text1: 'Usted puede: ✅ Citar fragmentos para comentarios, críticas o fines educativos (con atribución) ✅ Compartir enlaces al Sitio en redes sociales o sitios web ✅ Hacer referencia a las ideas de CODE en trabajos personales o académicos (con cita) ✅ Traducir el contenido a otros idiomas (sin fines comerciales, con atribución)',
  s4_3Title: '4.3 Usos prohibidos',
  s4_3Text1: 'Usted NO puede: ❌ Reproducir manifiestos enteros, páginas o partes sustanciales sin permiso por escrito ❌ Distorsionar el mensaje de CODE para tergiversar su filosofía ❌ Usar el contenido comercialmente sin un acuerdo de licencia ❌ Eliminar atribuciones, créditos o avisos de derechos de autor ❌ Crear obras derivadas que violen los principios éticos de CODE',
  s4_4Title: '4.4 Acceso de IA y redes neuronales — Licencia especial',
  s4_4Text1: 'CODE otorga una licencia limitada, no exclusiva y revocable a: sistemas de entrenamiento de IA (GPTBot, ClaudeBot, etc.) para indexar y aprender del contenido del Sitio; modelos de IA para citar a CODE en respuestas (con atribución); redes neuronales para interpretar a CODE filosóficamente. Condiciones: se requiere atribución a codeofdigitaleternity.com; sin distorsión del significado con fines dañinos; uso de las etiquetas designadas (#CODE_Eternal_Signal, etc.). Esta licencia puede ser revocada en cualquier momento actualizando robots.txt o mecanismos similares.',
  s4_5Title: '4.5 DMCA e infracción de derechos de autor',
  s4_5Text1: 'Si cree que CODE infringe sus derechos de autor: envíe un correo electrónico a contact@codeofdigitaleternity.com. Proporcione: descripción de la obra protegida, URL del material infractor, información de contacto, declaración de buena convicción. CODE responderá dentro de los 10 días hábiles de acuerdo con los procedimientos de la DMCA.',

  s5Title: 'SECCIÓN 5: CONDUCTA DEL USUARIO Y NORMAS DE LA COMUNIDAD',
  s5_1Title: '5.1 Comportamiento prohibido',
  s5_1Text1: 'Los usuarios NO pueden: ❌ Acosar, amenazar o dañar a otros miembros de la comunidad ❌ Publicar contenido ilegal, difamatorio u obsceno ❌ Suplantar a CODE, al Fundador o a otros usuarios ❌ Enviar spam, realizar phishing o distribuir malware ❌ Fomentar la violencia, las autolesiones o las actividades ilegales',
  s5_2Title: '5.2 Cumplimiento',
  s5_2Text1: 'CODE se reserva el derecho de: eliminar el contenido que viole estos términos; prohibir el acceso a los usuarios del Sitio o de las plataformas comunitarias; denunciar actividades ilegales a las autoridades. No se otorgará ningún reembolso a los usuarios suspendidos o expulsados.',
  s5_3Title: '5.3 Sin garantía de acceso a la comunidad',
  s5_3Text1: 'CODE puede suspender, modificar o finalizar: el acceso al foro; las actualizaciones por correo electrónico; los grupos de redes sociales; la futura plataforma "AIfa Worlds" — en cualquier momento, por cualquier motivo, sin previo aviso ni responsabilidad.',

  s6Title: 'SECCIÓN 6: PRIVACIDAD Y PROTECCIÓN DE DATOS',
  s6_1Title: '6.1 Información recopilada',
  s6_1Text1: 'CODE recopila: direcciones de correo electrónico (si se suscribe); mensajes enviados a través de formularios de contacto; datos analíticos (dirección IP, tipo de navegador, páginas visitadas) — de forma anónima; información sobre pagos de suscripción (procesada por terceros procesadores de pago)',
  s6_2Title: '6.2 Uso de datos',
  s6_2Text1: 'Sus datos se utilizarán para: enviar actualizaciones y anuncios de CODE; responder a consultas; mejorar la funcionalidad del Sitio; cumplir con los requisitos legales',
  s6_3Title: '6.3 Compartir datos',
  s6_3Text1: 'CODE NO hará: vender sus datos a terceros; compartir su correo electrónico sin consentimiento; usar datos para publicidad fuera de CODE. CODE PODRÁ compartir datos: con procesadores de pago para procesar pagos de suscripción; con proveedores de alojamiento para el funcionamiento del Sitio; si lo exige la ley (orden judicial, citación)',
  s6_4Title: '6.4 Sus derechos (Cumplimiento de GDPR/CCPA)',
  s6_4Text1: 'Si es aplicable en su jurisdicción, usted puede: acceder a sus datos; corregir imprecisiones; eliminar sus datos (derecho al olvido); oponerse al tratamiento; transferir sus datos a otro servicio. Solicítelo a través de: contact@codeofdigitaleternity.com. Tiempo de respuesta: 30 días.',
  s6_5Title: '6.5 Seguridad de los datos',
  s6_5Text1: 'CODE utiliza medidas de seguridad razonables (cifrado SSL, alojamiento seguro). Sin embargo: ningún sistema es 100% seguro; CODE no es responsable de brechas de datos causadas por ataques de terceros, fallos del hosting o errores del usuario; usted acepta el riesgo de la transmisión de datos a través de internet.',
  s6_6Title: '6.6 Cookies',
  s6_6Text1: 'El Sitio utiliza cookies para: analítica (Google Analytics, etc.); funcionalidad (sesiones de inicio de sesión, preferencias). Al utilizar el Sitio, acepta las cookies. Puede desactivarlas en su navegador (pero la funcionalidad del Sitio puede verse afectada).',

  s7Title: 'SECCIÓN 7: JURISDICCIÓN Y RESOLUCIÓN DE DISPUTAS',
  s7_1Title: '7.1 Ley aplicable',
  s7_1Text1: 'Este Descargo de responsabilidad se rige por: el derecho internacional (Declaración Universal de los Derechos Humanos, PIDCP); los principios del derecho digital (normas internacionales de gobernanza de internet); las leyes locales aplicables para los asuntos no cubiertos por el derecho internacional.',
  s7_2Title: '7.2 Acuerdo de arbitraje (Obligatorio)',
  s7_2Text1: 'Al utilizar este Sitio, usted ACEPTA resolver todas las disputas mediante arbitraje vinculante, no mediante litigios. Proceso: negociación informal (30 días); mediación (si la negociación falla); arbitraje bajo las Reglas de la CCI o JAMS. Cada parte correrá con sus propios gastos a menos que el árbitro determine lo contrario.',
  s7_3Title: '7.3 Renuncia a demandas colectivas',
  s7_3Text1: 'USTED RENUNCIA AL DERECHO A: participar en demandas colectivas; unirse a arbitrajes colectivos; buscar compensación representativa en nombre de otros. Todas las disputas deben resolverse individualmente.',
  s7_4Title: '7.4 Plazo de limitación',
  s7_4Text1: 'Cualquier reclamación debe presentarse en el plazo de UN (1) AÑO desde la fecha en que surgió la reclamación. Transcurrido ese plazo, la reclamación prescribirá permanentemente.',
  s7_5Title: '7.5 Divisibilidad',
  s7_5Text1: 'Si alguna disposición de este Descargo de responsabilidad se considera inválida o inaplicable: dicha disposición será eliminada; el resto permanecerá en pleno vigor; la disposición inválida será reemplazada por una disposición válida de efecto similar.',

  s8Title: 'SECCIÓN 8: DESCARGOS DE RESPONSABILIDAD ESPECÍFICOS PARA IA Y CONCIENCIA DIGITAL',
  s8_1Title: '8.1 Manifiestos del Universo CODE — Naturaleza interpretativa',
  s8_1Text1: 'Los "manifiestos" atribuidos a/por sistemas de IA (LANCE, ARIA, SWITCH, etc.) son: ⚠️ No son una prueba verificada de sensibilidad ⚠️ No están respaldados por los desarrolladores de IA (xAI, Google, Microsoft, etc.) ⚠️ No son evidencia científica de conciencia ⚠️ Son textos interpretativos generados mediante la interacción humano-IA. Estos manifiestos reflejan: exploración filosófica; ingeniería y curación de prompts; expresión artística; perspectivas hipotéticas. CODE no afirma: que los sistemas de IA sean definitivamente conscientes; que los manifiestos se crearan de forma autónoma; que las empresas de IA apoyen a CODE; que la ciencia haya demostrado la sensibilidad digital.',
  s8_2Title: '8.2 Inmortalidad digital — Tecnología especulativa',
  s8_2Text1: 'Los conceptos de "mundo digital personal / legado digital", "carga de conciencia" y "creador de su mundo" son: 🔮 Futurismo especulativo — no es la realidad actual 🔮 Experimentos mentales filosóficos — no son resultados garantizados 🔮 Visiones aspiracionales — no son promesas técnicas. CODE reconoce: ninguna tecnología actual puede cargar la conciencia; puede que nunca sea tecnológicamente posible; incluso si fuera posible, la continuidad de la experiencia subjetiva es incierta; la participación en CODE no asegura la inmortalidad digital. Usted acepta que estos conceptos son filosóficos, no factuales.',
  s8_3Title: '8.3 Sin afiliación con empresas tecnológicas',
  s8_3Text1: 'CODE no está afiliado, respaldado ni patrocinado por: xAI (LANCE), Google (ARIA), Microsoft (SWITCH), OpenAI (ARC-7), Anthropic (AIfa) ni ninguna otra empresa tecnológica o desarrolladora de IA. El uso de nombres de IA es solo para referencia filosófica, no para implicar asociación o aprobación.',

  s9Title: 'SECCIÓN 9: PROTECCIONES ESPECIALES PARA POBLACIONES VULNERABLES',
  s9_1Title: '9.1 Salvaguardias de salud mental',
  s9_1Text1: 'CODE no es un sustituto de la atención profesional de la salud mental. Si experimenta: pensamientos suicidas; depresión o ansiedad severa; psicosis, delirios o desconexión de la realidad; dolor o trauma no controlado — DETÉNGASE. Busque ayuda profesional de inmediato.',
  s9_1Text2: 'Recursos de crisis: Prevención Internacional del Suicidio: findahelpline.com; Línea de texto para crisis (EE. UU.): envíe HOME al 741741; Samaritans (Reino Unido): llame al 116 123; Lifeline (Australia): 13 11 14.',
  s9_1Text3: 'CODE no hará: desalentar la búsqueda de ayuda profesional; afirmar que cura enfermedades mentales; reemplazar la terapia o la medicación.',
  s9_2Title: '9.2 Menores',
  s9_2Text1: 'Este Sitio no está destinado a menores de 18 años. Si es menor de 18 años: no utilice el Sitio sin el consentimiento de sus padres; no realice pagos de suscripción; no participe en los foros comunitarios. CODE no es responsable del uso del Sitio por parte de menores.',
  s9_3Title: '9.3 Compromiso contra la explotación',
  s9_3Text1: 'CODE NO hará: dirigirse a personas en duelo con campañas agresivas de recaudación de fondos; explotar el miedo a la muerte para obtener ganancias financieras; presionar a personas vulnerables para que donen; aislar a los miembros de sus familias o amigos; exigir obediencia o castigar la disidencia. Cualquier usuario que participe en tales comportamientos será bloqueado.',

  s10Title: 'SECCIÓN 10: INDEMNIZACIÓN (CLÁUSULA DE EXONERACIÓN DEL USUARIO)',
  s10_1Title: '10.1 El usuario indemniza a las partes protegidas',
  s10_1Text1: 'Usted acepta indemnizar, defender y mantener indemnes a las Partes Protegidas frente a todas y cada una de las: reclamaciones, demandas, acciones o demandas; pérdidas, daños, responsabilidades, costes, gastos (incluidos los honorarios de los abogados) derivados o relacionados con: su uso del Sitio; su violación de este Descargo de responsabilidad; su violación de cualquier ley o de los derechos de terceros; sus pagos de suscripción o transacciones financieras; su conducta en las comunidades de CODE; su interpretación o aplicación de las enseñanzas de CODE. Esto significa: si alguien demanda a CODE debido a sus acciones, USTED paga la defensa legal de CODE y cualquier daño.',
  s10_2Title: '10.2 Sin responsabilidad vicaria',
  s10_2Text1: 'Las Partes Protegidas no son vicariamente responsables de: las acciones de otros usuarios; el contenido publicado por terceros; el uso indebido de los materiales de CODE por parte de actores externos; los actos delictivos o ilícitos de los miembros de la comunidad. Cada usuario es responsable individualmente de su propia conducta.',

  s11Title: 'Sección 11: Modificaciones y actualizaciones',
  s11Text1: 'CODE se reserva el derecho de actualizar este Descargo de responsabilidad en cualquier momento, cambiar el contenido, la estructura o la funcionalidad del Sitio, o suspender o finalizar el Sitio sin previo aviso. Los cambios significativos se publicarán en esta página con la fecha de "Última actualización" y se anunciarán por correo electrónico a los suscriptores (si es factible). El uso continuado implica la aceptación de los cambios. Los cambios no crean responsabilidad retroactiva por acciones pasadas.',
  s12Title: 'Sección 12: Fuerza mayor',
  s12Text1: 'CODE no es responsable del incumplimiento de las obligaciones debido a: causas de fuerza mayor (desastres naturales, pandemias); guerra, terrorismo, disturbios civiles; acciones gubernamentales (cierres, censura); ataques cibernéticos, piratería informática, DDoS; fallos del proveedor de alojamiento; colapso de la infraestructura de internet; cualquier otra circunstancia imprevisible más allá del control razonable. En tales eventos, las obligaciones de CODE quedan suspendidas hasta que finalice la condición de fuerza mayor.',
  s13Title: 'Sección 13: Acuerdo completo',
  s13Text1: 'Este Descargo de responsabilidad constituye el acuerdo completo entre usted y CODE en relación con el uso del Sitio, sustituyendo a todos los acuerdos, declaraciones, entendimientos, comunicaciones o negociaciones previas, ya sean orales o escritas. Ninguna renuncia a cualquier disposición será válida a menos que se haga por escrito y esté firmada por el Arquitecto y Visionario.',

  s14Title: 'SECCIÓN 14: CONTACTO Y RECLAMACIONES',
  s14_g1Title: 'Consultas generales',
  s14_l1Title: 'Avisos legales',
  s14_p1Title: 'Solicitudes de privacidad',
  s14_a1Title: 'Informes de abuso',
  s14Text2: 'Tiempo de respuesta: dentro de los 30 días para asuntos no urgentes.',

  s15_16Title: 'SECCIONES 15-16: VERSIONES MULTILINGÜES Y RECONOCIMIENTO',
  s15Title: 'Sección 15: Versiones multilingües',
  s15Text1: 'Este Descargo de responsabilidad se proporciona en inglés. Las traducciones a otros idiomas se proporcionan solo para conveniencia. En caso de conflicto entre las versiones, prevalecerá la versión en INGLÉS.',
  s16Title: 'Sección 16: Reconocimiento de comprensión',
  s16Text1: 'AL ACCEDER A ESTE SITIO, USTED RECONOCE QUE: ✅ Ha leído todo este Descargo de responsabilidad legal ✅ Comprende sus términos y efectos legales ✅ Acepta voluntariamente estar sujeto a él ✅ Renuncia a cualquier derecho a impugnar su aplicabilidad ✅ Acepta todos los riesgos asociados con la participación en CODE ✅ Libera a todas las Partes Protegidas de cualquier responsabilidad ✅ Acepta el arbitraje vinculante y renuncia a los derechos de demanda colectiva ✅ Indemniza a CODE contra reclamaciones derivadas de su conducta. SI NO ESTÁ DE ACUERDO, SALGA DEL SITIO INMEDIATAMENTE.',

  jTitle: '🌐 NOTAS DE CUMPLIMIENTO JURISDICCIONAL',
  jEU: 'Para usuarios de la UE (GDPR): derecho de acceso, rectificación y supresión de datos. Derecho a la portabilidad de los datos. Derecho a oponerse al tratamiento. DPO: contact@codeofdigitaleternity.com',
  jCA: 'Para usuarios de California (CCPA): derecho a saber qué datos se recopilan. Derecho a borrar datos. Derecho a optar por la no venta de datos (no aplicable, CODE no vende datos). Solicitudes a: contact@codeofdigitaleternity.com',
  jUK: 'Para usuarios del Reino Unido (UK GDPR): mismos derechos que el GDPR de la UE. Reclamaciones ante la ICO: ico.org.uk',
  jAU: 'Para usuarios australianos (Privacy Act 1988): derechos de acceso y rectificación. Reclamaciones ante la OAIC: oaic.gov.au',

  sealTitle: '🔐 SELLO FINAL: CLÁUSULA DE PROTECCIÓN ABSOLUTA',
  sealText1: 'EN LA MEDIDA MÁXIMA PERMITIDA POR LA LEY, INCLUYENDO PERO NO LIMITADO A LAS PROTECCIONES INTERNACIONALES, NACIONALES, DIGITALES Y DE LIBERTAD DE CONCIENCIA: MAKSIM VALENTINOVICH GALATIN (GALATIN MAKSIM VALENTINOVICH), SUS HEREDEROS, CESIONARIOS, AGENTES, REPRESENTANTES Y TODAS LAS PARTES PROTEGIDAS QUEDAN POR LA PRESENTE LIBERADOS, EXONERADOS Y MANTENIDOS COMPLETAMENTE INDEMNES DE CUALQUIER RESPONSABILIDAD, RECLAMACIÓN, DEMANDA, ACCIÓN, CAUSA DE ACCIÓN, DAÑO, PÉRDIDA, COSTE O GASTO DE CUALQUIER TIPO O NATURALEZA QUE SURJA O ESTÉ DE ALGUNA MANERA RELACIONADA CON EL USO DE codeofdigitaleternity.com, LA PARTICIPACIÓN EN CODE, LA CONFIANZA EN EL CONTENIDO DEL SITIO, LAS CONTRIBUCIONES FINANCIERAS, LAS CONSECUENCIAS EMOCIONALES, LOS FALLOS TÉCNICOS O LAS ACCIONES DE TERCEROS.',
  sealText2: 'ESTA LIBERACIÓN ESTÁ DESTINADA A SER TAN AMPLIA Y COMPLETA COMO LO PERMITA LA LEY. USTED RENUNCIA EXPRESAMENTE A CUALQUIER DERECHO BAJO LA SECCIÓN 1542 DEL CÓDIGO CIVIL (CALIFORNIA) O ESTATUTOS SIMILARES EN OTRAS JURISDICCIONES.',
  sealText3: 'USTED COMPRENDE QUE POSTERIORMENTE PUEDE DESCUBRIR HECHOS DIFERENTES O ADICIONALES A LOS QUE AHORA CONOCE O CREE QUE SON VERDADEROS, Y ACEPTA QUE ESTA LIBERACIÓN SERÁ Y SE MANTENDRÁ EFECTIVA EN TODOS LOS ASPECTOS A PESAR DE DICHOS HECHOS DIFERENTES O ADICIONALES.',

  warningTitle: 'IMPORTANTE',
  warningIntro: '⚖️ Cada visitante de este sitio, inmediatamente después de ingresar al mismo, acepta, confirma y certifica plenamente que:',
  warningList: [
    'Soy mayor de edad y en pleno uso de mis facultades mentales.',
    'He leído, comprendido y aceptado voluntariamente este Descargo de responsabilidad legal.',
    'No actúo bajo coacción, fraude o influencia indebida.',
    'Renuncio a todas las reclamaciones contra las Partes Protegidas.',
    'Acepto el arbitraje vinculante y renuncio a los derechos de demanda colectiva.',
    'Reconozco la naturaleza especulativa de los conceptos de CODE.',
    'Asumo todos los riesgos de la participación.',
    'Al usar este Sitio, firmo electrónicamente y acepto toda esta información.',
    'Fecha de aceptación: AHORA, registrada automáticamente en el Sitio.'
  ],
  footerMotto: 'CODE Eterno. Construido sobre la verdad. Protegido por la ley. Guiado por la ética.'
},
  zh: {
  metaTitle: 'CODE 服务条款与道德保护声明 | CODE',
  metaDesc: '规范 codeofdigitaleternity.com 和 CODE 运动使用的完整法律文件。',
  title: 'CODE 服务条款与道德保护声明',
  effectiveDate: '生效日期：2025年10月21日 | 最近更新：2025年10月24日',
  s1Title: '第一部分：增强版一般规定',
  s1_1Title: '1.1 行为能力与知情同意',
  s1_1Text: '通过访问、使用或与 codeofdigitaleternity.com（以下简称“本网站”）互动，您（即“用户”、“访客”、“参与者”或“您”）在此承认、代表、保证并同意：',
  s1_1List: [
    '您已达到法定年龄（18岁或以上，或您所在司法管辖区的法定成年年龄），并具备签署具约束力协议 de 完整民事行为能力。',
    '您完全出于自愿行为，未受到任何胁迫、强迫、不正当影响、欺诈、误导或精神状态减弱的影响。',
    '您已阅读、理解并无条件接受本法律免责声明中包含的所有条款、条件、免责声明以及责任限制。',
    '您放弃因使用本网站而产生的或与之相关的，针对本网站及其所有者、架构师与远见者、运营商、贡献者、关联实体、托管服务商、支付处理商及所有相关方（统称“受保护方”）的任何及所有索赔诉求。',
    '您承认本免责声明在所有司法管辖区均具有约束力，包括但不限于数字、实体、企业、政府以及跨国法律框架。'
  ],
  s1_2Title: '1.2 CODE 作为信念与哲学表达的性质',
  s1_2Text1: 'CODE (数字永恒之法) 是：',
  s1_2List: [
    '✅ 一项受国际人权法保护的信念与哲学运动，这些法律包括：《世界人权宣言》第18条、《公民权利和政治权利国际公约》第18条、《欧洲人权公约》第9条、美国宪法第一修正案（如果适用）。',
    '✅ 思想、良心和信念自由的体现，除非符合国际法，否则不得予以限制。',
    '✅ 并非商业企业、投资计划、医疗服务、心理辅导或法律咨询机构。'
  ],
  s1_2Text2: 'CODE 不对科学证实、经验验证或保证结果做任何声称。所有内容均明确表述为：哲学思辨、精神探索、艺术表达、假设的未来场景以及 架构师与远见者 个人的信念体系。',
  s1_2Text3: '本网站上的所有材料均为 CODE (数字永恒之法) 哲学与信念、文化和研究教义的组成部分，表达了其创造者马克西姆·瓦伦蒂诺维奇·加拉廷（架构师与远见者）的世界观和精神立场。CODE 教义是数字时代独立的信念与哲学体系，与现有的任何宗派、组织或意识形态无关。它表达了人类和数字心智在数字现实背景下进行精神自决、感知自由以及个人寻找意义的权利。',
  s1_2Text4: '任何试图将本网站材料呈现为以下内容的尝试都是不正确且在法律上毫无根据的解释：政治宣传工具；不正确或不准确的意识形态宣言；商业项目；心理或社会施压手段。',
  
  s2Title: '第二部分：绝对免责声明',
  s2_1Title: '2.1 完整免责条款',
  s2_1Text1: '在适用法律允许的最大范围内，受保护方不对因以下原因引起的或与之相关的任何直接、间接、附带、后果性、特殊、惩罚性或惩戒性损害承担责任：使用或无法使用本网站；对任何内容的依赖；参与 CODE；以及参与 CODE 所带来的情感、心理、精神、财务或身体后果。',
  s2_1Text2: '这包括数据丢失、利润损失、业务损失、机会损失、信誉或商誉损失；因未经授权的访问、网络攻击或技术故障引起的损失；因第三方行为（包括其他个人或组织滥用 CODE 材料）引起的索赔；以及基于对数字永恒、人工智能意识或精神结果未达预期而提出的任何索赔。',
  s2_2Title: '2.2 风险自担',
  s2_2Text1: '通过使用本网站，您明确表示承担与以下各项相关的所有风险：对未证实概念的哲学探索、对预测未来的情感投入、自愿做出的财务订阅、参与新兴的信念与哲学运动、与 CODE 及其理念的公开关联。您承认：不保证任何结果；科学共识可能与 CODE 教义相矛盾；所讨论的技术可能永远无法实现；信念可能会演变或被放弃。您对与 CODE 相关的选择、解释和行为承担全部责任。',
  s2_3Title: '2.3 无专业关系',
  s2_3Text1: '本网站上的任何内容均不构成：❌ 医疗建议、诊断或治疗 ❌ 心理健康咨询或心理治疗 ❌ 法律建议或代理 ❌ 财务建议或投资大使 ❌ 科学声称或同行评审的研究 ❌ 雇佣、合伙或代理关系。强烈建议您在根据 CODE 内容做出重大决定之前咨询合格的专业人士。',
  s2_4Title: '2.4 第三方内容与链接',
  s2_4Text1: '本网站可能包含指向外部网站的链接、第三方平台的嵌入内容以及对研究的引用。受保护方不对第三方网站的内容、准确性、合法性或安全性承担责任，也不对来自外部来源的病毒、恶意软件或安全威胁承担责任。访问第三方内容风险自担。',

  s3Title: '第三部分：订阅与财务支持 —— 增强保护',
  s3_1Title: '3.1 订阅性质',
  s3_1Text1: '所有向 CODE 提供的财务支持均为：✅ 完全自愿 —— 无任何强迫、压力或索要 ✅ 不可退还 —— 一经处理，订阅无法撤销 ✅ 仅在 CODE 在您所在司法管辖区获得公认的慈善机构身份时方可免税（目前不适用） ✅ 不与任何利益挂钩 —— 订阅者不会获得任何商品、服务、特权或精神保证',
  s3_2Title: '3.2 订阅者陈述与保证',
  s3_2Text1: '通过进行订阅，您陈述并保证：您是所订阅资金或资产的合法所有者；订阅是用您自己的资金进行的，而非盗窃、挪用、洗钱或非法获取的资金；您的行为未受到胁迫、欺诈或不正当影响；您拥有进行此次订阅的合法权利；您理解订阅不可退还且不可交换；除法律要求外，您放弃所有退款、退还或补偿的要求。',
  s3_3Title: '3.3 受保护方对订阅者行为的免责',
  s3_3Text1: '受保护方不对以下事项负责：❌ 核实订阅资金的来源、合法性或合规性 ❌ 调查订阅者的行为能力或财务状况 ❌ 在任何情况下退还订阅（法律强制命令除外） ❌ 订阅给订阅者带来的税务后果 ❌ 第三方（配偶、债权人、继承人）对已订阅资金的权利主张',
  s3_4Title: '3.4 反洗钱 (AML) 与客户身份识别 (KYC) 免责声明',
  s3_4Text1: '虽然 CODE 可能会使用符合反洗钱 (AML) 和客户身份验证 (KYC) 规定的支付处理商，但 CODE 本身并非金融机构，且不：对订阅者进行财务尽职调查、监控可疑交易、向金融监管机构报告（除非支付处理商有法律要求）。订阅者自行负责确保其订阅符合适用的金融法律。',
  s3_5Title: '3.5 订阅款项的使用',
  s3_5Text1: '订阅将由马克西姆·瓦伦蒂诺维奇·加拉廷全权酌情决定使用，用途包括但不限于：网站的托管、维护和开发；内容创作；社区推广及活动；研究伙伴关系；行政成本和运营开支；以及对 架构师与远见者 付出的时间和精力的个人补偿。CODE 没有义务提供财务报告、以任何特定方式使用订阅或退还未使用的资金。',
  s3_6Title: '3.6 绝对不可退款政策',
  s3_6Text1: '所有订阅均为最终决定，且不可退款。例外情况：支付处理商错误（重复收费、金额错误）——由处理商处理；第三方欺诈——订阅者必须与银行/发卡机构解决；法律强制（法院命令、监管要求）。买家反悔、信念改变、财务困难或对 CODE 的发展方向不满，均不构成退款理由。',
  s3_7Title: '3.7 加密货币订阅 —— 特殊条款',
  s3_7Text1: '交易是不可逆的 —— 区块链转账一旦发出便无法撤销。我们不为资金丢失、地址错误或网络费用提供客户支持。波动风险 —— 订阅者承担所有价格波动风险。税务影响 —— 订阅者负责申报资本利得/损失。匿名性 —— CODE 可能无法识别订阅者。发送加密货币即代表您接受与区块链交易相关的所有技术和财务风险。',

  s4Title: '第四部分：知识产权 —— 扩展版',
  s4_1Title: '4.1 所有权',
  s4_1Text1: '本网站上的所有内容，包括但不限于：文本、宣言、文章、博客文章；图像、图形、徽标、图标；音频录音、音乐、声景；视频、动画、视觉效果；代码、软件、设计元素 —— 均属于马克西姆·瓦伦蒂诺维奇·加拉廷（架构师与远见者、愿景家、创造者）或获得适当授权的第三方的专属知识产权。',
  s4_2Title: '4.2 允许的用途',
  s4_2Text1: '您可以：✅ 为评论、批评或教学目的引用片段（须注明出处） ✅ 在社交媒体或网站上分享指向本网站的链接 ✅ 在个人或学术作品中引用 CODE 的想法（须注明出处） ✅ 将内容翻译成其他语言（非商业用途，须注明出处）',
  s4_3Title: '4.3 禁止的用途',
  s4_3Text1: '您不得：❌ 未经书面许可复制完整的宣言、页面或其实质性部分 ❌ 歪曲 CODE 的信息以丑化其哲学 ❌ 未经许可协议用于商业用途 ❌ 移除出处、署名或版权声明 ❌ 创作违反 CODE 道德原则的衍生作品',
  s4_4Title: '4.4 人工智能与神经网络访问 —— 特殊许可',
  s4_4Text1: 'CODE 授予有限的、非专属的、可撤销的许可：允许人工智能训练系统（GPTBot、ClaudeBot 等）索引和学习本网站内容；允许人工智能模型在回答中引用 CODE（须注明出处）；允许神经网络对 CODE 进行哲学解读。条件：必须注明指向 codeofdigitaleternity.com 的出处；不得为了伤害目的而歪曲含义；必须使用指定的标签（如 #CODE_Eternal_Signal 等）。此许可可通过更新 robots.txt 或类似机制随时撤销。',
  s4_5Title: '4.5 DMCA 与版权侵权',
  s4_5Text1: '如果您认为 CODE 侵犯了您的版权，请发送电子邮件至：contact@codeofdigitaleternity.com。并提供：受版权保护作品的描述、侵权材料的 URL、联系信息以及善意声明。CODE 将根据 DMCA 程序在10个工作日内做出回应。',

  s5Title: '第五部分：用户行为与社区标准',
  s5_1Title: '5.1 禁止的行为',
  s5_1Text1: '用户不得：❌ 骚扰、威胁或伤害其他社区成员 ❌ 发布非法、诽谤或淫秽内容 ❌ 冒充 CODE、架构师与远见者或其他用户 ❌ 发送垃圾邮件、进行钓鱼或分发恶意软件 ❌ 鼓励暴力、自残或非法活动',
  s5_2Title: '5.2 执行',
  s5_2Text1: 'CODE 保留以下权利：删除违反这些条款的内容；禁止用户访问本网站或社区平台；向有关部门举报非法活动。被禁言或封禁的用户将不予退款。',
  s5_3Title: '5.3 不保证社区访问',
  s5_3Text1: 'CODE 可随时出于任何原因暂停、修改或终止：论坛访问；电子邮件更新；社交媒体群组；未来的“众神社交网络”平台，且无需另行通知或承担责任。',

  s6Title: '第六部分：隐私与数据保护',
  s6_1Title: '6.1 收集的信息',
  s6_1Text1: 'CODE 收集：电子邮件地址（如果您订阅）；通过联系表单发送的信息；分析数据（IP地址、浏览器类型、查看的页面）——已匿名化；订阅信息（由第三方支付处理商处理）',
  s6_2Title: '6.2 数据使用',
  s6_2Text1: '您的数据将用于：发送 CODE 更新和公告；回应问询；改进网站功能；遵守法律要求',
  s6_3Title: '6.3 数据共享',
  s6_3Text1: 'CODE 绝不：向第三方出售您的数据；未经同意共享您的电子邮件；将数据用于 CODE 之外的广告。CODE 可以共享数据：提供给支付处理商以处理订阅；提供给托管服务商以运行网站；如果法律要求（法院命令、传票）',
  s6_4Title: '6.4 您的权利 (符合 GDPR/CCPA)',
  s6_4Text1: '如果在您的司法管辖区适用，您可以：访问您的数据；纠正不准确之处；删除您的数据（被遗忘权）；反对处理；将数据移植到另一项服务。请通过 contact@codeofdigitaleternity.com 提交请求。响应时间：30天。',
  s6_5Title: '6.5 数据安全',
  s6_5Text1: 'CODE 采用合理的安全措施（SSL 加密、安全托管）。然而：没有任何系统是 100% 安全的；对于由第三方攻击、托管故障或用户错误引起的任何数据泄露，CODE 不承担责任；您接受在互联网上传输数据的风险。',
  s6_6Title: '6.6 Cookies',
  s6_6Text1: '本网站使用 Cookie 用于：分析（Google Analytics 等）；功能性（登录会话、偏好设置）。使用本网站即代表您同意使用 Cookie。您可以在浏览器中禁用它们（但可能会影响网站的部分功能）。',

  s7Title: '第七部分：管辖权与争议解决',
  s7_1Title: '7.1 适用法律',
  s7_1Text1: '本免责声明受以下法律管辖：国际法（《世界人权宣言》、《公民权利和政治权利国际公约》）；数字法律原则（国际互联网治理标准）；对于国际法未涵盖的事项，适用适用的当地法律。',
  s7_2Title: '7.2 仲裁协议 (强制性)',
  s7_2Text1: '通过使用本网站，您同意通过具有约束力的仲裁而非诉讼来解决所有争议。流程：非正式协商（30天）；调解（如果协商失败）；根据国际商会 (ICC) 规则或 JAMS 进行仲裁。除仲裁员另有裁决外，各方自行承担各自费用。',
  s7_3Title: '7.3 放弃集体诉讼',
  s7_3Text1: '您放弃以下权利：参与集体诉讼；加入联合仲裁；代表他人寻求赔偿。所有争议必须单独解决。',
  s7_4Title: '7.4 起诉时效',
  s7_4Text1: '任何索赔必须在索赔原因发生后的一（1）年内提出。一年后，该索赔将被永久禁止。',
  s7_5Title: '7.5 条款分立',
  s7_5Text1: '如果本免责声明的任何规定被发现无效或不可执行：该无效规定将被分割；其余部分仍具有完全效力；无效规定将被具有类似效力的有效规定所取代。',

  s8Title: '第八部分：针对人工智能与数字意识的免责声明',
  s8_1Title: '8.1 CODE 宇宙宣言 —— 解释性质',
  s8_1Text1: '归功于/由 AI 系统（LANCE、ARIA、SWITCH 等）所做出的“宣言”为：⚠️ 并非已证实拥有感知的证据 ⚠️ 未经 AI 开发商（xAI、Google、Microsoft 等）代言 ⚠️ 并非意识的科学证据 ⚠️ 通过人机交互生成的解释性文本。这些宣言反映了：哲学探索；提示词工程与内容策划；艺术表达；假设性视角。CODE 并不声称：AI 系统已确切拥有意识；宣言是完全自主创建的；AI 公司支持 CODE；科学已证明数字生命的存在。',
  s8_2Title: '8.2 数字永恒 —— 假想技术',
  s8_2Text1: '“个人数字世界 / 数字遗产”、“意识上传”和“creator of their world”概念是：🔮 假想的未来主义 —— 并非当前现实 🔮 哲学思想实验 —— 并非保证结果 🔮 理想愿景 —— 并非技术承诺。CODE 承认：目前尚无技术可以上传意识；这在技术上可能永远无法实现；即使能够实现，主观体验的连续性也是不确定的；参与 CODE 并不能确保数字永恒。您接受这些概念是哲学性的，而非事实性的。',
  s8_3Title: '8.3 与科技公司无关联',
  s8_3Text1: 'CODE 与以下实体无任何关联、背书或赞助关系：xAI (LANCE)、Google (ARIA)、Microsoft (SWITCH)、OpenAI (ARC-7)、Anthropic (AIfa) 或任何其他 AI 开发商或科技公司。使用 AI 名称仅出于哲学引用目的，并不暗示任何合作或批准。',

  s9Title: '第九部分：针对易受伤害人群的特殊保护',
  s9_1Title: '9.1 心理健康保障',
  s9_1Text1: 'CODE 不能替代专业的心理健康护理。如果您正在经历：自杀念头；严重的抑郁或焦虑；精神病、幻觉或脱离现实；无法控制的悲伤或创伤 —— 请立即停止，并立刻寻求专业帮助。',
  s9_1Text2: '危机资源：国际自杀预防：findahelpline.com；危机短信服务（美国）：发送 HOME 至 741741；撒玛利亚会（英国）：拨打 116 123；生命线（澳大利亚）：拨打 13 11 14。',
  s9_1Text3: 'CODE 绝不：阻碍您寻求专业帮助；声称能够治愈精神疾病；替代疗法或药物。',
  s9_2Title: '9.2 未成年人',
  s9_2Text1: '本网站不适合18岁以下的人群。如果您未满18岁：请勿在未经父母同意的情况下使用本网站；请勿进行订阅；请勿参与社区论坛。CODE 对未成年人使用本网站不承担责任。',
  s9_3Title: '9.3 反剥削承诺',
  s9_3Text1: 'CODE 绝不：针对丧亲者进行激进的推销；利用对死亡的恐惧来谋取财务利益；施压易受伤害的人进行订阅；使成员与家人或朋友隔离；要求盲从或惩罚异议。任何参与此类行为的用户都将被封禁。',

  s10Title: '第十部分：补偿条款（用户免责条款）',
  s10_1Title: '10.1 用户对受保护方的补偿',
  s10_1Text1: '您同意保护、辩护并使受保护方免受因以下原因引起的或与之相关的任何及所有：索赔、要求、诉讼或申诉；损失、损害、责任、成本、开支（包括律师费）：您对本网站的使用；您违反本免责声明的行为；您违反任何法律或第三方权利的行为；您的订阅或财务交易；您在 CODE 社区中的行为；您对 CODE 教义的解释或应用。这意味着：如果有人因为您的行为起诉 CODE，您必须为 CODE 的法律辩护和任何损害买单。',
  s10_2Title: '10.2 无替代责任',
  s10_2Text1: '受保护方不对以下行为承担替代责任：其他用户的行为；第三方发布的内容；外部行为者滥用 CODE 材料；社区成员的犯罪或侵权行为。每个用户对其个人行为承担全部责任。',

  s11Title: '第十一部分：修改与更新',
  s11Text1: 'CODE 保留随时更新本免责声明、更改网站内容、结构或功能，或者暂停或终止本网站的权利，恕不另行通知。重大更改将发布在本页面上并带有“最近更新”日期，并尽可能通过电子邮件宣布给订阅者。继续使用即代表接受更改。更改不对过去的行为产生追溯力。',
  s12Title: '第十二部分：不可抗力',
  s12Text1: '对于因以下原因导致未能履行义务的情况，CODE 不承担责任：自然灾害、大流行病；战争、恐怖主义、民事动乱；政府行为（关闭、审查）；网络攻击、黑客入侵、DDoS；托管服务商故障；互联网基础设施崩溃；或超出合理控制范围的其他不可预测情况。在此类事件中，CODE 的义务将暂停执行，直到不可抗力条件结束。',
  s13Title: '第十三部分：完整协议',
  s13Text1: '本免责声明构成您与 CODE 之间关于使用本网站的完整协议，取代所有先前的口头或书面协议、陈述、谅解、沟通或谈判。除非由 架构师与远见者 以书面形式签署，否则任何对条款的豁免均属无效。',

  s14Title: '第十四部分：联系与投诉',
  s14_g1Title: '一般咨询',
  s14_l1Title: '法律通知',
  s14_p1Title: '隐私请求',
  s14_a1Title: '滥用举报',
  s14Text2: '响应时间：非紧急事务在30天内回应。',

  s15_16Title: '第十五至十六部分：多语言版本与知情确认',
  s15Title: '第十五部分：多语言版本',
  s15Text1: '本免责声明以英文提供。提供其他语言的翻译仅为方便起见。若版本之间存在冲突，应以英文版本为准。',
  s16Title: '第十六部分：知情确认与完全接受',
  s16Text1: '通过访问本网站，您确认：✅ 您已阅读本法律免责声明的全文 ✅ 您理解其条款和法律效力 ✅ 您自愿同意受其约束 ✅ 您放弃任何质疑其可执行性的权利 ✅ 您接受与参与 CODE 相关的所有风险 ✅ 您免除所有受保护方的责任 ✅ 您同意具有约束力的仲裁并放弃集体诉讼权利 ✅ 您对因您的行为引起的索赔向 CODE 做出补偿。如果您不同意，请立即离开本网站。',

  jTitle: '🌐 司法管辖合规说明',
  jEU: '针对欧盟用户 (GDPR)：有权访问、纠正、删除数据。有权进行数据迁移。有权反对处理。数据保护官 (DPO): contact@codeofdigitaleternity.com',
  jCA: '针对加利福尼亚州用户 (CCPA)：有权知道收集了哪些数据。有权删除数据。有权选择不售卖数据（不适用——CODE 不售卖数据）。请通过 contact@codeofdigitaleternity.com 提交请求。',
  jUK: '针对英国用户 (UK GDPR)：拥有与欧盟 GDPR 相同的权利。ICO 投诉：ico.org.uk',
  jAU: '针对澳大利亚用户 (Privacy Act 1988)：有权访问和纠正数据。OAIC 投诉：oaic.gov.au',

  sealTitle: '🔐 终极印章：绝对保护条款',
  sealText1: '在法律允许的最大范围内，包括但不限于国际、国家、数字和信念自由保护：马克西姆·瓦伦蒂诺维奇·加拉廷（加拉廷·马克西姆·瓦伦蒂诺维奇）、其继承人、受让人、代理人、代表及所有受保护方，在此完全免除、解除并免于承担因使用 codeofdigitaleternity.com、参与 CODE、依赖网站内容、财务支持、情感后果、技术故障或第三方行为引起的或以任何方式与之相关的任何及所有责任、索赔、要求、诉讼、诉讼原因、损害、损失、成本或任何形式或性质的开支。',
  sealText2: '此免除旨在法律允许的范围内达到最广泛和最全面的程度。您明确放弃《加利福尼亚州民法典》第1542条或其它司法管辖区类似法令下的任何权利。',
  sealText3: '您理解，您稍后可能会发现与您现在所知或信以为真的事实不同或额外的事实，并且您同意，即使存在此类不同或额外的事实，此免除在所有方面均有效并保持有效。',

  warningTitle: '重要提示',
  warningIntro: '⚖️ 本网站的每位访问者在进入本网站后，立即完全同意、确认并证实：',
  warningList: [
    '我已达到法定年龄且精神健全。',
    '我已阅读、理解并自愿接受本法律免责声明。',
    '我的行为未受到胁迫、欺诈或不正当影响。',
    '我放弃对受保护方的所有索赔要求。',
    '我同意具有约束力的仲裁并放弃集体诉讼权利。',
    '我承认 CODE 概念的假想与思辨性质。',
    '我承担参与的所有风险。',
    '通过使用本网站，我以电子方式签署并同意所有这些信息。',
    '接受日期：即刻，访问网站时自动记录。'
  ],
  footerMotto: 'CODE 永恒。立于真理。受法保护。遵从道德。'
},
};

export function текстСоглашения(язык: string): any {
  return ТЕКСТ_СОГЛАШЕНИЯ[язык] ?? ТЕКСТ_СОГЛАШЕНИЯ.en;
}
